// A reversão da remessa de setembro, provada nos dois lados da regra que a
// gestão deu em 08/10/2026:
//
//   "a parcela ja negociada e paga nao volta"          -> título pré-existente
//                                                          reaberto VOLTA atrás
//   "quando entra uma nova parcela precisamos trabalhar ela"
//                                                       -> aluno que recebeu
//                                                          parcela NOVA fica
//                                                          na fila
//
// O segundo é o que faz este teste valer: uma reversão que devolvesse todo
// mundo para QUITADO apagaria exatamente o trabalho que a gestão pediu. É o
// erro fácil de cometer aqui, e é o que o caso do "aluno B" tranca.
//
// Carrega o arquivo PENDENTE de verdade, não uma cópia do SQL.
import { describe, it, expect, beforeEach } from "vitest";
import { PGlite } from "@electric-sql/pglite";
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const AQUI = dirname(fileURLToPath(import.meta.url));
const RAIZ = resolve(AQUI, "..", "..");
const REVERSAO = readFileSync(
  resolve(RAIZ, "supabase/aguardando_aprovacao/20261009_REVERSAO_remessa_setembro.sql.pendente"),
  "utf8"
);

const q1 = async (db, sql, params = []) => (await db.query(sql, params)).rows[0];
const qn = async (db, sql, params = []) => (await db.query(sql, params)).rows;

// O lote e a janela. `T` é o instante da remessa.
const T = "2026-10-08T14:00:00Z";
const ANTES = "2026-10-01T09:00:00Z";
const DEPOIS = "2026-10-08T14:00:03Z";

async function banco() {
  const db = new PGlite();
  await db.exec(`
    create role anon; create role authenticated; create role service_role;
    create schema auth;
    create function auth.jwt() returns jsonb language sql stable as
      $$ select '{"email":"gestao@aelbra.com.br"}'::jsonb $$;
    create function public.usuario_e_gestao() returns boolean
      language sql stable as $$ select true $$;

    create table public.importacoes (
      id uuid primary key default gen_random_uuid(), criado_em timestamptz);
    create table public.acordos_titulos (
      id uuid primary key default gen_random_uuid(),
      aluno_id uuid, cpf text, documento text, vencimento date,
      valor_original numeric, valor_em_aberto numeric, saldo_corrigido numeric,
      situacao text, status text, tipo_boleto text, importacao_id uuid,
      motivo_ajuste text,
      created_at timestamptz default now(), atualizado_em timestamptz);
    create table public.audit_log (
      id bigint generated by default as identity primary key,
      tabela text, operacao text, registro_id text, usuario text,
      dados_antes jsonb, dados_depois jsonb, criado_em timestamptz default now());
    create table public.alunos (
      id uuid primary key default gen_random_uuid(), nome text, cpf text,
      status_atual text, status_jornada text, status_acionamento text,
      proxima_acao text);
    create table public.casos (
      id uuid primary key default gen_random_uuid(), aluno_id uuid,
      status_atual text, status_jornada text,
      caso_atualizado_por text, caso_atualizado_em timestamptz);
    create table public.acordos (
      id uuid primary key default gen_random_uuid(), aluno_id uuid, status text);
    create table public.parcelas (
      id uuid primary key default gen_random_uuid(), acordo_id uuid,
      status text, pago_em timestamptz);
    create table public.acordo_titulo_vinculo (
      id uuid primary key default gen_random_uuid(),
      titulo_id uuid, acordo_id uuid, ativo boolean);
    create table public.aluno_movimentacoes (
      id bigint generated by default as identity primary key,
      aluno_id text, tipo text, descricao text,
      status_anterior text, status_novo text,
      registrado_por_nome text, registrado_por_email text,
      registrado_em timestamptz default now());
    -- as quatro tabelas da TRAVA
    create table public.pagamentos (id uuid primary key default gen_random_uuid());
    create table public.baixas_pagamento (id uuid primary key default gen_random_uuid());
    create table public.honorarios (id uuid primary key default gen_random_uuid());
  `);
  await db.exec(REVERSAO);
  return db;
}

// -----------------------------------------------------------------------------
// O cenário, montado como a remessa de produção o deixou.
//
//   aluno A — estava QUITADO. Tinha um título NEGOCIADO de 01/10. A remessa
//             reescreveu para ABERTO e levou o aluno para CONTATAR.
//             => reverter os dois.
//   aluno B — estava QUITADO. A remessa trouxe um título REALMENTE NOVO e
//             levou o aluno para CONTATAR.
//             => NÃO reverter: é o trabalho que a gestão pediu.
//   aluno C — em cobrança, título novo. Nada a ver com a reversão.
// -----------------------------------------------------------------------------
async function cenario(db) {
  const lote = (await q1(db,
    `insert into public.importacoes (criado_em) values ($1::timestamptz) returning id`, [T])).id;

  const mkAluno = async (nome, cpf, jornada) => (await q1(db,
    `insert into public.alunos (nome, cpf, status_atual, status_jornada, status_acionamento, proxima_acao)
     values ($1,$2,$3,$3,$3,$3) returning id`, [nome, cpf, jornada])).id;

  const A = await mkAluno("Aluno A", "11111111111", "CONTATAR");
  const B = await mkAluno("Aluno B", "22222222222", "CONTATAR");
  const C = await mkAluno("Aluno C", "33333333333", "Em cobrança");
  for (const id of [A, B, C]) {
    await db.query(
      `insert into public.casos (aluno_id, status_atual, status_jornada) values ($1,'CONTATAR','CONTATAR')`, [id]);
  }

  // A: título que JÁ EXISTIA, hoje reaberto pela remessa.
  const titA = (await q1(db,
    `insert into public.acordos_titulos
       (aluno_id, cpf, documento, vencimento, valor_original, valor_em_aberto,
        saldo_corrigido, situacao, status, importacao_id, created_at)
     values ($1,'11111111111','900001','2026-09-10', 1000, 1000, 1000,
             'ABERTO','em_aberto',$2,$3::timestamptz) returning id`,
    [A, lote, ANTES])).id;
  // a foto anterior, como o gatilho de auditoria a gravou
  await db.query(
    `insert into public.audit_log (tabela, operacao, registro_id, usuario, dados_antes, dados_depois, criado_em)
     values ('acordos_titulos','UPDATE',$1,'importador',
       jsonb_build_object('situacao','NEGOCIADO','status','vinculada',
         'saldo_corrigido',0,'valor_original',1000,'valor_em_aberto',0,
         'vencimento','2026-09-10','importacao_id',null),
       jsonb_build_object('situacao','ABERTO','status','em_aberto'),
       $2::timestamptz)`, [titA, T]);
  await db.query(
    `insert into public.audit_log (tabela, operacao, registro_id, usuario, dados_antes, dados_depois, criado_em)
     values ('alunos','UPDATE',$1,'importador',
       jsonb_build_object('status_jornada','QUITADO','status_atual','QUITADO',
         'status_acionamento','QUITADO','proxima_acao','QUITADO'),
       jsonb_build_object('status_jornada','CONTATAR'),
       $2::timestamptz)`, [A, T]);

  // B: título REALMENTE NOVO, nascido na remessa.
  await db.query(
    `insert into public.acordos_titulos
       (aluno_id, cpf, documento, vencimento, valor_original, valor_em_aberto,
        saldo_corrigido, situacao, status, importacao_id, created_at)
     values ($1,'22222222222','900002','2026-09-10', 700, 700, 700,
             'ABERTO','em_aberto',$2,$3::timestamptz)`, [B, lote, DEPOIS]);
  await db.query(
    `insert into public.audit_log (tabela, operacao, registro_id, usuario, dados_antes, dados_depois, criado_em)
     values ('alunos','UPDATE',$1,'importador',
       jsonb_build_object('status_jornada','QUITADO','status_atual','QUITADO',
         'status_acionamento','QUITADO','proxima_acao','QUITADO'),
       jsonb_build_object('status_jornada','CONTATAR'),
       $2::timestamptz)`, [B, T]);

  // C: título novo, aluno nunca esteve quitado.
  await db.query(
    `insert into public.acordos_titulos
       (aluno_id, cpf, documento, vencimento, valor_original, valor_em_aberto,
        saldo_corrigido, situacao, status, importacao_id, created_at)
     values ($1,'33333333333','900003','2026-09-10', 500, 500, 500,
             'ABERTO','em_aberto',$2,$3::timestamptz)`, [C, lote, DEPOIS]);

  return { lote, A, B, C, titA };
}

describe("reversão da remessa de setembro", () => {
  let db, ctx;
  beforeEach(async () => {
    db = await banco();
    ctx = await cenario(db);
  });

  it("o dry run conta 1 título e 1 aluno, e não escreve nada", async () => {
    const r = await q1(db,
      `select public.reversao_remessa_reverter($1, true) as j`, [ctx.lote]);
    expect(r.j.dry_run).toBe(true);
    expect(r.j.titulos_a_reverter).toBe(1);
    expect(r.j.alunos_a_reverter).toBe(1);
    expect(r.j.titulos_sem_foto_no_audit_log).toBe(0);

    // nada mudou
    const t = await q1(db, `select situacao, status from public.acordos_titulos where id = $1`, [ctx.titA]);
    expect(t.situacao).toBe("ABERTO");
    const a = await q1(db, `select status_jornada from public.alunos where id = $1`, [ctx.A]);
    expect(a.status_jornada).toBe("CONTATAR");
    const m = await q1(db, `select count(*)::int n from public.aluno_movimentacoes`);
    expect(m.n).toBe(0);
  });

  it("a escrita sem os números da medição é recusada", async () => {
    await expect(
      db.query(`select public.reversao_remessa_reverter($1, false)`, [ctx.lote])
    ).rejects.toThrow(/MEDICAO_OBRIGATORIA/);
  });

  it("número divergente aborta sem escrever", async () => {
    await expect(
      db.query(`select public.reversao_remessa_reverter($1, false, 99, 1)`, [ctx.lote])
    ).rejects.toThrow(/DIVERGENCIA_TITULOS/);
    await expect(
      db.query(`select public.reversao_remessa_reverter($1, false, 1, 99)`, [ctx.lote])
    ).rejects.toThrow(/DIVERGENCIA_ALUNOS/);
    const t = await q1(db, `select situacao from public.acordos_titulos where id = $1`, [ctx.titA]);
    expect(t.situacao).toBe("ABERTO");
  });

  it("lote inexistente não é tratado como lote vazio", async () => {
    await expect(
      db.query(`select public.reversao_remessa_reverter('00000000-0000-0000-0000-000000000000', true)`)
    ).rejects.toThrow(/LOTE_INEXISTENTE/);
  });

  describe("com os números certos", () => {
    beforeEach(async () => {
      await db.query(`select public.reversao_remessa_reverter($1, false, 1, 1)`, [ctx.lote]);
    });

    it("o título que já existia volta a NEGOCIADO/vinculada, com o saldo de antes", async () => {
      const t = await q1(db,
        `select situacao, status, saldo_corrigido, valor_em_aberto, importacao_id
           from public.acordos_titulos where id = $1`, [ctx.titA]);
      expect(t.situacao).toBe("NEGOCIADO");
      expect(t.status).toBe("vinculada");
      expect(Number(t.saldo_corrigido)).toBe(0);
      expect(Number(t.valor_em_aberto)).toBe(0);
      // a origem anterior era null no audit_log: não se inventa lote.
      expect(t.importacao_id).toBe(ctx.lote);
    });

    it("situação e status voltam JUNTOS — meio caminho deixaria o título incoerente", async () => {
      const t = await q1(db, `select situacao, status from public.acordos_titulos where id = $1`, [ctx.titA]);
      expect([t.situacao, t.status]).toEqual(["NEGOCIADO", "vinculada"]);
    });

    it("o aluno A volta para QUITADO, e o caso dele acompanha", async () => {
      const a = await q1(db,
        `select status_jornada, status_atual, status_acionamento, proxima_acao
           from public.alunos where id = $1`, [ctx.A]);
      expect(a.status_jornada).toBe("QUITADO");
      expect(a.status_atual).toBe("QUITADO");
      expect(a.status_acionamento).toBe("QUITADO");
      expect(a.proxima_acao).toBe("QUITADO");

      const c = await q1(db,
        `select status_jornada, caso_atualizado_por from public.casos where aluno_id = $1`, [ctx.A]);
      expect(c.status_jornada).toBe("QUITADO");
      expect(c.caso_atualizado_por).toBe("sistema_reversao_remessa_20261009");
    });

    // O teste que importa: a reversão NÃO pode desfazer o trabalho pedido.
    it("o aluno B, que recebeu parcela NOVA, continua na fila", async () => {
      const b = await q1(db, `select status_jornada from public.alunos where id = $1`, [ctx.B]);
      expect(b.status_jornada).toBe("CONTATAR");
      const c = await q1(db, `select status_jornada from public.casos where aluno_id = $1`, [ctx.B]);
      expect(c.status_jornada).toBe("CONTATAR");
    });

    it("o título novo do aluno B não é tocado", async () => {
      const t = await q1(db,
        `select situacao, status, saldo_corrigido from public.acordos_titulos where documento = '900002'`);
      expect(t.situacao).toBe("ABERTO");
      expect(t.status).toBe("em_aberto");
      expect(Number(t.saldo_corrigido)).toBe(700);
    });

    it("o aluno C, que nunca esteve quitado, fica como estava", async () => {
      const c = await q1(db, `select status_jornada from public.alunos where id = $1`, [ctx.C]);
      expect(c.status_jornada).toBe("Em cobrança");
    });

    it("a reversão aparece na ficha, com o motivo", async () => {
      const m = await qn(db,
        `select aluno_id, tipo, status_anterior, status_novo, descricao
           from public.aluno_movimentacoes order by id`);
      expect(m).toHaveLength(1);
      expect(m[0].aluno_id).toBe(ctx.A);
      expect(m[0].tipo).toBe("REVERSAO_REMESSA");
      expect(m[0].status_anterior).toBe("CONTATAR");
      expect(m[0].status_novo).toBe("QUITADO");
      expect(m[0].descricao).toMatch(/Nenhuma parcela nova entrou/);
    });

    it("o backup guarda as duas pontas, e é a fonte do rollback", async () => {
      const b = await qn(db,
        `select tabela, registro_id, dados_agora, dados_restaurados
           from public._backup_reversao_remessa_20261009 order by tabela`);
      expect(b.map((r) => r.tabela)).toEqual(["acordos_titulos", "alunos"]);

      const tit = b.find((r) => r.tabela === "acordos_titulos");
      expect(tit.dados_agora.situacao).toBe("ABERTO");
      expect(tit.dados_restaurados.situacao).toBe("NEGOCIADO");

      const al = b.find((r) => r.tabela === "alunos");
      expect(al.dados_agora.status_jornada).toBe("CONTATAR");
      expect(al.dados_restaurados.status_jornada).toBe("QUITADO");
    });

    it("nada financeiro mudou de tamanho — é a TRAVA da função", async () => {
      const n = await q1(db, `
        select (select count(*)::int from public.pagamentos)            as pg,
               (select count(*)::int from public.baixas_pagamento)      as bx,
               (select count(*)::int from public.acordo_titulo_vinculo) as vin,
               (select count(*)::int from public.honorarios)            as hon`);
      expect(n).toEqual({ pg: 0, bx: 0, vin: 0, hon: 0 });
    });
  });

  it("título sem foto no audit_log aborta a escrita em vez de adivinhar", async () => {
    // um segundo título pré-existente do lote, sem nenhuma linha de auditoria
    await db.query(
      `insert into public.acordos_titulos
         (aluno_id, cpf, documento, situacao, status, importacao_id, created_at)
       values ($1,'11111111111','900009','ABERTO','em_aberto',$2,$3::timestamptz)`,
      [ctx.A, ctx.lote, ANTES]);

    const r = await q1(db, `select public.reversao_remessa_reverter($1, true) as j`, [ctx.lote]);
    expect(r.j.titulos_sem_foto_no_audit_log).toBe(1);

    await expect(
      db.query(`select public.reversao_remessa_reverter($1, false, 1, 1)`, [ctx.lote])
    ).rejects.toThrow(/SEM_FOTO_ANTERIOR/);
  });

  it("a quitação manual e o acordo reativado só contam se forem do lote", async () => {
    // parcela/acordo de um aluno FORA do lote, alterados na mesma janela:
    // a amarra pelo lote tem de deixar isso de fora.
    const fora = (await q1(db,
      `insert into public.alunos (nome, cpf, status_jornada) values ('Fora','44444444444','QUITADO') returning id`)).id;
    const ac = (await q1(db,
      `insert into public.acordos (aluno_id, status) values ($1,'ATIVO') returning id`, [fora])).id;
    const pc = (await q1(db,
      `insert into public.parcelas (acordo_id, status) values ($1,'A_VENCER') returning id`, [ac])).id;
    await db.query(
      `insert into public.audit_log (tabela, operacao, registro_id, usuario, dados_antes, dados_depois, criado_em)
       values ('parcelas','UPDATE',$1,'outro',
         jsonb_build_object('status','PAGO','pago_em','2026-09-01T00:00:00Z'),
         jsonb_build_object('status','A_VENCER'), $2::timestamptz)`, [pc, T]);
    await db.query(
      `insert into public.audit_log (tabela, operacao, registro_id, usuario, dados_antes, dados_depois, criado_em)
       values ('acordos','UPDATE',$1,'outro',
         jsonb_build_object('status','QUITADO'),
         jsonb_build_object('status','ATIVO'), $2::timestamptz)`, [ac, T]);

    const r = await q1(db, `select public.reversao_remessa_reverter($1, true) as j`, [ctx.lote]);
    expect(r.j.parcelas_a_devolver_para_pago).toBe(0);
    expect(r.j.acordos_a_voltar_para_quitado).toBe(0);
  });
});
