// QUEM SAIU DA EQUIPE SOME DO TELÃO — comportamento, no banco.
//
// Roda a migration REAL 20261007103000 contra um Postgres de verdade (pglite) e
// confere o payload que sai de tv_snapshot_atualizar(). O que estes casos
// protegem:
//
//   1. Olga (cobranca03) sai de TODOS os rankings e destaques de uma vez, via
//      v_ops — e os colegas continuam lá;
//   2. elogio dela não entra no telão nem se for aprovado;
//   3. música dela sai da Playlist ReATIVA;
//   4. aniversário e card de destaque saem do ar sem serem apagados;
//   5. NENHUM número financeiro muda — recuperado, honorários e meta somam
//      pagamentos inteiro, incluindo os dela;
//   6. a migration é idempotente e aborta se a âncora não existir.
//
// NENHUM DADO REAL de aluno. Os operadores são os e-mails de serviço da equipe.
import { describe, it, expect, beforeAll, vi } from "vitest";
import { PGlite } from "@electric-sql/pglite";
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// Subir uma instância pglite do zero passa dos 5 s padrão do vitest.
vi.setConfig({ testTimeout: 180000, hookTimeout: 600000 });

const AQUI = dirname(fileURLToPath(import.meta.url));
const ler = (p) => readFileSync(resolve(AQUI, "..", "..", p), "utf8");
const MIGRATION = ler("supabase/migrations/20261007103000_tv_equipe_oculta_sem_olga.sql");

const OLGA = "cobranca03@aelbra.com.br";
const COLEGA = "cobranca05@aelbra.com.br";
const GESTAO = "amanda.seibel@aelbra.com.br";

// Andaime: as tabelas que as duas funções tocam, e versões reduzidas de
// tv_snapshot_calcular/atualizar com os MESMOS trechos que a migration ancora —
// v_ops, a consulta de elogios e a de playlist. O resto do cálculo fica de fora
// porque não é o que está sob teste.
const ANDAIME = `
create schema if not exists auth;
create or replace function auth.jwt() returns jsonb language sql stable as $$
  select coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb, '{}'::jsonb) $$;
create or replace function auth.email() returns text language sql stable as $$ select auth.jwt()->>'email' $$;
create or replace function auth.role() returns text language sql stable as $$
  select coalesce(auth.jwt()->>'role','authenticated') $$;
do $$ begin
  if not exists (select 1 from pg_roles where rolname='authenticated') then create role authenticated; end if;
  if not exists (select 1 from pg_roles where rolname='anon') then create role anon; end if;
end $$;

create table public.tv_snapshot (
  id boolean primary key default true, versao bigint not null default 0, payload jsonb,
  status text, gerado_em timestamptz, gerado_por text, duracao_ms int, erro_resumo text);
create table public.tv_config (chave text primary key, valor jsonb, ativo boolean default true);
create table public.tv_aniversariantes (
  id bigint generated by default as identity primary key, nome text not null,
  dia integer, mes integer not null, ativo boolean not null default true);
create table public.portal_playlist (
  id uuid primary key default gen_random_uuid(), titulo text, artista text,
  adicionado_por text, adicionado_por_email text, criado_em timestamptz default now(),
  ativo boolean default true);
create table public.portal_eventos (
  id uuid primary key default gen_random_uuid(), titulo text, inicio_em timestamptz,
  categoria text, ativo boolean default true);
create table public.pagamentos (
  id bigint generated by default as identity primary key, data_pagamento date,
  valor_pago numeric, valor_honorario numeric, operador_email text, operador_nome text, cpf text);
create table public.aluno_movimentacoes (
  id bigint generated by default as identity primary key, status_novo text,
  elogio_aprovado_tv boolean default false, registrado_por_nome text,
  registrado_por_email text, registrado_em timestamptz default now(), elogio_print_path text);

create or replace function public.tv_snapshot_calcular()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare
  v_rec bigint; v_hon bigint; v_elogios jsonb; v_aniv jsonb; v_rank jsonb;
  v_ops text[] := array['cobranca03@aelbra.com.br','cobranca05@aelbra.com.br','cobranca06@aelbra.com.br',
                        'cobranca08@aelbra.com.br','cobranca10@aelbra.com.br','cobranca11@aelbra.com.br',
                        'cobranca12@aelbra.com.br','cobranca13@aelbra.com.br'];
  v_hoje date := (now() at time zone 'America/Sao_Paulo')::date;
begin
  -- FINANCEIRO: soma pagamentos INTEIRO, sem v_ops. É isto que não pode mudar.
  select coalesce(round(sum(valor_pago)),0)::bigint, coalesce(round(sum(valor_honorario)),0)::bigint
    into v_rec, v_hon from public.pagamentos where data_pagamento is not null;

  -- VITRINE: tudo aqui passa por v_ops.
  v_rank := jsonb_build_object(
    'ranking_mes', coalesce((select jsonb_agg(jsonb_build_object('operador', op, 'valor', vl) order by vl desc)
      from (select upper(coalesce(operador_nome, operador_email)) op, round(sum(valor_pago)) vl
              from public.pagamentos where lower(operador_email) = any(v_ops)
             group by 1) r), '[]'::jsonb),
    'melhor_mes', (select jsonb_build_object('operador', op) from (
        select upper(coalesce(operador_nome, operador_email)) op, sum(valor_pago) v
          from public.pagamentos where lower(operador_email) = any(v_ops)
         group by 1 order by v desc limit 1) a),
    'allowlist', to_jsonb(v_ops));

  select coalesce(jsonb_agg(jsonb_build_object('id',id,'registrado_por_nome',registrado_por_nome)
           order by registrado_em desc), '[]'::jsonb)
    into v_elogios
  from (select id, registrado_por_nome, registrado_em, elogio_print_path from public.aluno_movimentacoes
    where status_novo = 'ELOGIO_ATENDIMENTO' and elogio_aprovado_tv = true order by registrado_em desc limit 20) e;

  select coalesce(jsonb_agg(jsonb_build_object('nome', nome, 'dia', dia) order by nome), '[]'::jsonb)
    into v_aniv from public.tv_aniversariantes
  where ativo = true and mes = extract(month from v_hoje);

  return jsonb_build_object(
    'mes', jsonb_build_object('recuperado', v_rec, 'honorarios', v_hon),
    'rank', v_rank, 'elogios', v_elogios, 'aniversariantes', v_aniv);
end;
$function$;

create or replace function public.tv_snapshot_atualizar()
returns jsonb language plpgsql security definer set search_path to 'public'
set statement_timeout to '30s' as $function$
declare v_payload jsonb;
begin
  insert into public.tv_snapshot (id) values (true) on conflict (id) do nothing;
  v_payload := public.tv_snapshot_calcular();

  v_payload := v_payload || jsonb_build_object(
    'aniversario_destaque',
    (select valor from public.tv_config where chave = 'aniversario_destaque' and ativo = true limit 1));

  v_payload := v_payload || jsonb_build_object(
    'playlist_reativa',
    coalesce((
      select jsonb_agg(to_jsonb(x) order by x.criado_em desc)
      from (
        select id, titulo, artista, adicionado_por, criado_em
        from public.portal_playlist
        where ativo = true
        order by criado_em desc
        limit 6
      ) x
    ), '[]'::jsonb));

  update public.tv_snapshot set versao = versao + 1, payload = v_payload, status = 'ok' where id = true;
  return jsonb_build_object('status','ok');
end;
$function$;
`;

// Dados: Olga e um colega pagando no mesmo mês; elogio, música, aniversário e
// card de destaque dela no ar.
const SEMENTE = `
insert into public.pagamentos (data_pagamento, valor_pago, valor_honorario, operador_email, operador_nome) values
  (current_date, 30000, 3000, '${OLGA}',   'OLGA'),
  (current_date, 20000, 2000, '${COLEGA}', 'NATALY');

insert into public.aluno_movimentacoes (status_novo, elogio_aprovado_tv, registrado_por_nome, registrado_por_email) values
  ('ELOGIO_ATENDIMENTO', true, 'OLGA',   '${OLGA}'),
  ('ELOGIO_ATENDIMENTO', true, 'NATALY', '${COLEGA}');

insert into public.portal_playlist (titulo, artista, adicionado_por, adicionado_por_email) values
  ('Musica da Olga',  'Artista A', 'OLGA',   '${OLGA}'),
  ('Musica da Nataly','Artista B', 'NATALY', '${COLEGA}');

insert into public.tv_aniversariantes (nome, dia, mes) values
  ('Olga Patricia de Oliveira', 15, extract(month from (now() at time zone 'America/Sao_Paulo')::date)),
  ('Nataly Souza',              20, extract(month from (now() at time zone 'America/Sao_Paulo')::date));

insert into public.tv_config (chave, valor, ativo) values
  ('aniversario_destaque', '{"nome":"OLGA PATRICIA","data":"2026-10-15","ativo":true}'::jsonb, true);
`;

async function novoBanco({ comMigration = true } = {}) {
  const db = new PGlite();
  await db.exec(ANDAIME);
  await db.exec(SEMENTE);
  if (comMigration) await db.exec(MIGRATION);
  await db.exec(`select set_config('request.jwt.claims','{"email":"${GESTAO}"}',false)`);
  return db;
}

async function atualizar(db) {
  await db.query("select public.tv_snapshot_atualizar()");
  const r = await db.query("select payload from public.tv_snapshot where id = true");
  return r.rows[0].payload;
}

const texto = (v) => JSON.stringify(v).toUpperCase();

let antes, depois;
beforeAll(async () => {
  const a = await novoBanco({ comMigration: false });
  antes = await atualizar(a);
  await a.close();
  depois = await novoBanco();
});

describe("a lista de quem não aparece no telão", () => {
  it("existe e nasce com a Olga", async () => {
    const r = await depois.query("select email, nome, motivo from public.tv_equipe_oculta order by email");
    expect(r.rows).toHaveLength(1);
    expect(r.rows[0].email).toBe(OLGA);
    expect(r.rows[0].nome).toBe("OLGA");
  });

  it("só aceita e-mail normalizado, e TRUNCATE não fica herdado", async () => {
    await expect(depois.query(
      "insert into public.tv_equipe_oculta(email, nome) values ('  Maiuscula@X.COM  ', 'X')"
    )).rejects.toThrow();
    const r = await depois.query(
      "select has_table_privilege('authenticated','public.tv_equipe_oculta','TRUNCATE') as pode");
    expect(r.rows[0].pode).toBe(false);
  });
});

describe("antes da migration, a Olga aparecia mesmo", () => {
  it("rankings, elogios, playlist, aniversário e destaque citavam o nome", async () => {
    expect(texto(antes.rank)).toContain("OLGA");
    expect(texto(antes.elogios)).toContain("OLGA");
    expect(texto(antes.playlist_reativa)).toContain("OLGA");
    expect(texto(antes.aniversariantes)).toContain("OLGA");
    expect(texto(antes.aniversario_destaque)).toContain("OLGA");
  });
});

describe("depois da migration, some de toda tela da TV", () => {
  it("o payload inteiro não cita mais a Olga", async () => {
    const p = await atualizar(depois);
    expect(texto(p)).not.toContain("OLGA");
    expect(texto(p)).not.toContain("COBRANCA03");
  });

  it("sai da allowlist — e os colegas continuam lá", async () => {
    const p = await atualizar(depois);
    expect(p.rank.allowlist).not.toContain(OLGA);
    expect(p.rank.allowlist).toContain(COLEGA);
    expect(p.rank.allowlist.length).toBe(7);
  });

  it("sai dos rankings e destaques; o colega assume", async () => {
    const p = await atualizar(depois);
    expect(texto(p.rank.ranking_mes)).not.toContain("OLGA");
    expect(p.rank.ranking_mes).toHaveLength(1);
    expect(p.rank.melhor_mes.operador).toBe("NATALY");  // era OLGA, que pagou mais
  });

  it("elogio dela não entra nem aprovado; o do colega fica", async () => {
    const p = await atualizar(depois);
    expect(texto(p.elogios)).not.toContain("OLGA");
    expect(texto(p.elogios)).toContain("NATALY");
  });

  it("música dela sai da playlist; a do colega fica", async () => {
    const p = await atualizar(depois);
    expect(texto(p.playlist_reativa)).not.toContain("OLGA");
    expect(texto(p.playlist_reativa)).toContain("NATALY");
  });

  it("aniversário e card de destaque saem do ar", async () => {
    const p = await atualizar(depois);
    expect(texto(p.aniversariantes)).not.toContain("OLGA");
    expect(texto(p.aniversariantes)).toContain("NATALY");
    expect(p.aniversario_destaque).toBeNull();
  });
});

describe("nada de histórico nem de dinheiro foi apagado", () => {
  it("os pagamentos dela continuam na tabela, intactos", async () => {
    const r = await depois.query(
      "select count(*)::int n, coalesce(sum(valor_pago),0)::text total from public.pagamentos where operador_email = $1", [OLGA]);
    expect(r.rows[0].n).toBe(1);
    expect(Number(r.rows[0].total)).toBe(30000);
  });

  it("recuperado e honorários do mês NÃO mudam — ela continua somando", async () => {
    const p = await atualizar(depois);
    expect(Number(p.mes.recuperado)).toBe(Number(antes.mes.recuperado));
    expect(Number(p.mes.honorarios)).toBe(Number(antes.mes.honorarios));
    expect(Number(p.mes.recuperado)).toBe(50000);   // 30.000 dela + 20.000 do colega
    expect(Number(p.mes.honorarios)).toBe(5000);
  });

  it("elogio, música e aniversário dela continuam no banco, só inativos", async () => {
    const e = await depois.query(
      "select count(*)::int n from public.aluno_movimentacoes where registrado_por_email = $1", [OLGA]);
    expect(e.rows[0].n).toBe(1);

    const m = await depois.query(
      "select count(*)::int n from public.portal_playlist where adicionado_por_email = $1", [OLGA]);
    expect(m.rows[0].n).toBe(1);

    const a = await depois.query(
      "select ativo from public.tv_aniversariantes where upper(nome) like '%OLGA%'");
    expect(a.rows).toHaveLength(1);
    expect(a.rows[0].ativo).toBe(false);

    const c = await depois.query(
      "select ativo from public.tv_config where chave = 'aniversario_destaque'");
    expect(c.rows[0].ativo).toBe(false);
  });
});

describe("a migration se comporta", () => {
  it("rodar de novo não quebra nem muda nada", async () => {
    const def = async () => (await depois.query(`
      select pg_get_functiondef(p.oid) src from pg_proc p join pg_namespace n on n.oid = p.pronamespace
       where n.nspname='public' and p.proname='tv_snapshot_calcular'`)).rows[0].src;
    const a = await def();
    await depois.exec(MIGRATION);
    expect(await def()).toBe(a);
    const linhas = await depois.query("select count(*)::int n from public.tv_equipe_oculta");
    expect(linhas.rows[0].n).toBe(1);
  });

  it("basta um INSERT para esconder a próxima pessoa — sem migration nova", async () => {
    await depois.query(
      "insert into public.tv_equipe_oculta(email, nome) values ($1, 'NATALY') on conflict do nothing", [COLEGA]);
    const p = await atualizar(depois);
    expect(texto(p.elogios)).not.toContain("NATALY");
    expect(texto(p.playlist_reativa)).not.toContain("NATALY");
    await depois.query("delete from public.tv_equipe_oculta where email = $1", [COLEGA]);
  });

  it("sem a âncora de v_ops, aborta em vez de mexer às cegas", async () => {
    const b = await novoBanco({ comMigration: false });
    await b.exec(`
      create or replace function public.tv_snapshot_calcular()
      returns jsonb language sql security definer set search_path to 'public'
      as $f$ select jsonb_build_object('mes', jsonb_build_object('recuperado', 1)) $f$;`);
    await expect(b.exec(MIGRATION)).rejects.toThrow(/ancora|aparece/i);
    await b.close();
  });
});

describe("o rollback devolve tudo", () => {
  it("desfaz os três filtros e a Olga volta aos rankings, elogios e playlist", async () => {
    const b = await novoBanco();
    const antesDoRollback = await atualizar(b);
    expect(texto(antesDoRollback)).not.toContain("OLGA");

    await b.exec(ler("supabase/rollbacks/20261007103000_tv_equipe_oculta_sem_olga.rollback.sql"));

    const p = await atualizar(b);
    expect(p.rank.allowlist).toContain(OLGA);
    expect(p.rank.allowlist.length).toBe(8);
    expect(texto(p.rank.ranking_mes)).toContain("OLGA");
    expect(texto(p.elogios)).toContain("OLGA");
    expect(texto(p.playlist_reativa)).toContain("OLGA");

    // A tabela some; as listas curadas seguem desligadas, como o arquivo avisa.
    const t = await b.query(
      "select to_regclass('public.tv_equipe_oculta') is null as sumiu");
    expect(t.rows[0].sumiu).toBe(true);
    const a = await b.query("select ativo from public.tv_aniversariantes where upper(nome) like '%OLGA%'");
    expect(a.rows[0].ativo).toBe(false);
    await b.close();
  });
});
