-- FIXTURE GERADA A PARTIR DA PRODUCAO em 2026-09-20T16:15:39.190706+00:00 (somente leitura: pg_get_functiondef, pg_attribute).

-- Funcoes: texto EXATO de producao, conferido por md5 do prosrc (protecao_confirmacao_prod_20260920.md5.json).

-- Tabelas: colunas e tipos de producao; sem NOT NULL/FK/indices (nao sao regra sob teste).

-- STUBS de infraestrutura (NAO sao regra de negocio): auth.jwt(), auth.role() e sistema_sob_carga() (le pg_stat_activity).

-- NENHUM DADO REAL. Substitui grupo_a_prod_20260918.sql, que esta desatualizado (md5 de caso_protegido_redistribuicao diverge).

create extension if not exists unaccent;
create schema if not exists auth;
create schema if not exists internal;

create or replace function auth.jwt() returns jsonb language sql stable as $$ select nullif(current_setting('test.jwt', true), '')::jsonb $$;

create or replace function auth.role() returns text language sql stable as $$ select coalesce(auth.jwt()->>'role','') $$;

create table public.acordo_titulo_vinculo (
  "id" uuid default gen_random_uuid() primary key,
  "acordo_id" uuid,
  "titulo_id" uuid,
  "ativo" boolean default true,
  "vinculado_por" text,
  "motivo_desvinculo" text,
  "criado_em" timestamp with time zone default now(),
  "origem" text
);

create table public.acordos (
  "id" uuid default gen_random_uuid() primary key,
  "aluno_id" uuid,
  "cpf" text,
  "tipo" text default 'ACORDO'::text,
  "forma_pagamento" text default 'PARCELADO'::text,
  "valor_total" numeric,
  "qtd_parcelas" integer default 1,
  "valor_entrada" numeric,
  "entrada_paga" boolean default false,
  "data_entrada" date,
  "status" text default 'ATIVO'::text,
  "observacao" text,
  "criado_por_nome" text,
  "criado_por_email" text,
  "confirmado_por_email" text,
  "confirmado_em" timestamp with time zone,
  "criado_em" timestamp with time zone default now(),
  "atualizado_em" timestamp with time zone default now(),
  "numero_acordo" bigint generated by default as identity,
  "operador_responsavel_email" text,
  "unidade" text,
  "entrada_percentual" numeric,
  "honorarios_percentual" numeric,
  "honorarios_valor" numeric,
  "saldo" numeric,
  "motivo_ajuste" text,
  "operador_responsavel_nome" text,
  "duplicado_de" uuid,
  "duplicado_marcado_em" timestamp with time zone,
  "numero_ulbra" text
);

create table public.acordos_titulos (
  "id" uuid default gen_random_uuid() primary key,
  "aluno_id" uuid,
  "cpf" text,
  "documento" text,
  "vencimento" date,
  "valor_original" numeric(14,2),
  "saldo_corrigido" numeric(14,2),
  "situacao" text,
  "tipo_boleto" text,
  "dados" jsonb,
  "importacao_id" uuid,
  "created_at" timestamp without time zone default now(),
  "status" text default 'em_aberto'::text,
  "valor_em_aberto" numeric,
  "competencia" text,
  "motivo_ajuste" text,
  "atualizado_em" timestamp with time zone default now(),
  "acordo_id" uuid,
  "vinculado_em" timestamp with time zone,
  "vinculado_por" text,
  "valor_cobranca_ajustado" numeric,
  "motivo_ajuste_valor" text,
  "valor_ajustado_por" text,
  "valor_ajustado_em" timestamp with time zone,
  "origem_liquidacao" text,
  "origem_liquidacao_ref" text,
  "origem_liquidacao_em" timestamp with time zone,
  "origem_encerramento" text,
  "origem_encerramento_ref" text,
  "origem_encerramento_em" timestamp with time zone
);

create table public.alunos (
  "id" uuid default gen_random_uuid() primary key,
  "cpf" text,
  "cpf_mascarado" text,
  "matricula" text,
  "nome" text,
  "email" text,
  "telefone" text,
  "curso" text,
  "unidade" text,
  "semestre" text,
  "situacao_academica" text,
  "status_jornada" text default 'Em cobrança'::text,
  "origem" text,
  "aluno_novo" boolean default false,
  "sem_telefone" boolean default false,
  "sem_email" boolean default false,
  "created_at" timestamp without time zone default now(),
  "updated_at" timestamp without time zone default now(),
  "nome_normalizado" text,
  "operador" text,
  "status_atual" text,
  "ultimo_contato" date,
  "data_retorno" date,
  "valor_em_aberto" numeric(12,2) default 0,
  "hora_retorno" text,
  "atualizado_em" timestamp with time zone default now(),
  "operador_nome" text,
  "operador_email" text,
  "observacao" text,
  "tipo_base" text,
  "nome_aluno" text,
  "nome_referencia" text,
  "cpf_corrigido" text,
  "cpf_status_correcao" text,
  "registro_unico" uuid default gen_random_uuid(),
  "chave_unificacao" text,
  "unificacao_status" text,
  "registrado_por_nome" text,
  "registrado_por_email" text,
  "registrado_em" timestamp with time zone,
  "responsavel_atual_nome" text,
  "responsavel_atual_email" text,
  "responsavel_atual_em" timestamp with time zone,
  "status_acionamento" text,
  "proxima_acao" text,
  "data_ultimo_acionamento" timestamp with time zone,
  "status_link_pagamento" text,
  "status_baixa_pagamento" text,
  "fila_destino" text,
  "ultimo_link_pagamento_id" uuid,
  "ultima_baixa_pagamento_id" uuid,
  "nivel_criticidade" text,
  "processo_numero" text,
  "processo_prazo_tipo" text,
  "processo_prazo_data" date,
  "nome_resp1" text,
  "telefone_resp1" text,
  "nome_resp2" text,
  "telefone_resp2" text,
  "situacao_operacional" text,
  "saldo_vencido" numeric,
  "saldo_total" numeric,
  "curso_real" text,
  "academico_codigo" text,
  "academico_fonte" text,
  "academico_atualizado_em" timestamp with time zone,
  "retorno_confirmado_em" timestamp with time zone,
  "retorno_origem" text,
  "semestre_divida" text,
  "semestre_divida_em" timestamp with time zone
);

create table public.alunos_unificados (
  "chave_unificacao" text,
  "nome_referencia" text,
  "nome_aluno" text,
  "cpf_referencia" text,
  "quantidade_cpfs" integer default 0,
  "quantidade_casos" integer default 0,
  "quantidade_links" integer default 0,
  "valor_total_casos" numeric default 0,
  "valor_total_links" numeric default 0,
  "status_unificacao" text,
  "atualizado_em" timestamp with time zone default now(),
  "operador_nome" text,
  "operador_email" text,
  "status_jornada" text default 'EM_COBRANCA'::text,
  "data_retorno" date,
  "hora_retorno" time without time zone,
  "prioridade_operacional" text default 'NORMAL'::text,
  "observacao_operacional" text,
  "ultima_interacao_em" timestamp with time zone,
  "ocultar_fila" boolean default false,
  "nome_aluno_editado" text,
  "cpf_referencia_editado" text,
  "telefone_aluno" text,
  "email_aluno" text,
  "curso_aluno" text,
  "unidade_aluno" text,
  "observacao_cadastro" text,
  "cadastro_atualizado_por" text,
  "cadastro_atualizado_em" timestamp with time zone,
  "atendimento_assumido_em" timestamp with time zone,
  "ultimo_operador_nome" text,
  "ultimo_operador_email" text,
  "status_atendimento" text,
  "retorno_origem" text
);

create table public.baixas_pagamento (
  "id" uuid default gen_random_uuid() primary key,
  "aluno_id" text,
  "solicitacao_link_id" uuid,
  "aluno_nome" text,
  "aluno_cpf" text,
  "valor_pago" numeric,
  "comprovante_url" text,
  "comprovante_nome_arquivo" text,
  "observacao_operador" text,
  "status_baixa" text default 'AGUARDANDO_BAIXA'::text,
  "operador_origem_nome" text,
  "operador_origem_email" text,
  "responsavel_baixa_nome" text default 'Amanda Seibel'::text,
  "responsavel_baixa_email" text default 'amanda.seibel@aelbra.com.br'::text,
  "recebido_em" timestamp with time zone default now(),
  "atualizado_em" timestamp with time zone default now(),
  "baixado_por_nome" text,
  "baixado_por_email" text,
  "baixado_em" timestamp with time zone,
  "devolvido_por_nome" text,
  "devolvido_por_email" text,
  "devolvido_em" timestamp with time zone,
  "motivo_devolucao" text,
  "parcela_id" uuid,
  "acordo_id" uuid,
  "honorarios_recebidos" numeric,
  "data_pagamento" date
);

create table public.casos (
  "id" uuid default gen_random_uuid() primary key,
  "caso_codigo" integer,
  "cpf_original" text,
  "cpf_limpo" text,
  "cpf_mascarado" text,
  "matricula" text,
  "nome" text,
  "nome_normalizado" text,
  "operador_base" text,
  "operador_mensalidade" text,
  "operador_acordo" text,
  "operador_acordo_planilha" text,
  "status_atual" text,
  "data_ultimo_acionamento" date,
  "status_acionamento" text,
  "criticidade" text,
  "proxima_acao_automatica" text,
  "total_em_aberto" numeric,
  "data_retorno" date,
  "dias_atraso" integer,
  "nivel_carteira" text,
  "sla_operacional" text,
  "urgencia" text,
  "observacoes" text,
  "mensalidades_em_aberto" numeric,
  "acordo_em_aberto" numeric,
  "parcela_a_vencer" numeric,
  "parcelas_vencidas" numeric,
  "proximo_vencimento" date,
  "valor_pago" numeric,
  "honorario" numeric,
  "data_pagamento" date,
  "status_financeiro" text,
  "observacao_financeira" text,
  "created_at" timestamp without time zone default now(),
  "data_retorno_nova" date,
  "ultima_tabulacao_em" timestamp without time zone,
  "fila_responsavel" text,
  "hora_retorno" time without time zone,
  "observacao_operacional" text,
  "status_termo" text default 'Sem termo'::text,
  "termo_status_validacao" text,
  "termo_url" text,
  "termo_nome_arquivo" text,
  "termo_observacao" text,
  "termo_motivo_rejeicao" text,
  "termo_enviado_por" text,
  "termo_validado_por" text,
  "termo_validado_em" timestamp with time zone,
  "nome_aluno" text,
  "cpf" text,
  "status_jornada" text,
  "operador" text,
  "observacao" text,
  "aluno" text,
  "nome_completo" text,
  "email" text,
  "telefone" text,
  "curso" text,
  "unidade" text,
  "semestre" text,
  "ultimo_acionamento" date,
  "valor_em_aberto" numeric,
  "valor_aberto" numeric,
  "valor_total" numeric,
  "valor_divida" numeric,
  "saldo_devedor" numeric,
  "valor" numeric,
  "origem" text,
  "operador_nome" text,
  "operador_email" text,
  "nome_referencia" text,
  "cpf_corrigido" text,
  "cpf_status_correcao" text,
  "registro_unico" uuid default gen_random_uuid(),
  "chave_unificacao" text,
  "unificacao_status" text,
  "origem_quitacao" text,
  "quitado_em" date,
  "valor_quitado" numeric default 0,
  "baixa_importada_id" uuid,
  "valor_cobranca_ajustado" numeric,
  "motivo_ajuste_valor" text,
  "valor_ajustado_por" text,
  "valor_ajustado_em" timestamp with time zone,
  "cadastro_caso_observacao" text,
  "caso_atualizado_por" text,
  "caso_atualizado_em" timestamp with time zone,
  "nao_acionar" boolean default false,
  "aluno_id" uuid,
  "nivelamento_marcador" text,
  "nivelamento_em" timestamp with time zone,
  "nivelamento_simulacao_id" uuid,
  "situacao_operacional" text,
  "saldo_vencido" numeric,
  "saldo_total" numeric,
  "encerrado_operacional" boolean default false,
  "operador_mensalidade_email" text,
  "operador_mensalidade_nome" text,
  "mensalidade_girada_em" timestamp with time zone
);

create table public.historico_operadores_alunos (
  "id" uuid default gen_random_uuid() primary key,
  "aluno_id" uuid,
  "chave_unificacao" text,
  "nome_aluno" text,
  "cpf_referencia" text,
  "acao" text,
  "operador_nome" text,
  "operador_email" text,
  "operador_anterior_nome" text,
  "operador_anterior_email" text,
  "status_jornada_anterior" text,
  "status_jornada_novo" text,
  "data_retorno_anterior" date,
  "data_retorno_nova" date,
  "observacao" text,
  "criado_em" timestamp with time zone default now()
);

create table public.links_pagamento (
  "id" uuid default gen_random_uuid() primary key,
  "aluno_id" text,
  "aluno_nome" text,
  "aluno_cpf" text,
  "operador_nome" text,
  "operador_email" text,
  "tipo_pagamento" text default 'Cartão'::text,
  "parcelas" integer,
  "valor" numeric,
  "vencimento" date,
  "link_url" text,
  "status" text default 'SOLICITADO'::text,
  "observacao_operador" text,
  "observacao_adm" text,
  "solicitado_por" text,
  "solicitado_em" timestamp with time zone default now(),
  "gerado_por" text,
  "gerado_em" timestamp with time zone,
  "enviado_em" timestamp with time zone,
  "pago_em" timestamp with time zone,
  "cancelado_em" timestamp with time zone,
  "atualizado_em" timestamp with time zone default now(),
  "baixado_por" text,
  "baixado_em" timestamp with time zone,
  "divergencia_motivo" text,
  "divergencia_em" timestamp with time zone,
  "comprovante_url" text,
  "comprovante_nome" text,
  "pagamento_identificado_por" text,
  "pagamento_identificado_em" timestamp with time zone,
  "nome_referencia" text,
  "cpf_corrigido" text,
  "cpf_status_correcao" text,
  "registro_unico" uuid default gen_random_uuid(),
  "chave_unificacao" text,
  "unificacao_status" text,
  "nome_aluno" text,
  "cpf_referencia" text,
  "forma_pagamento" text,
  "observacao_solicitacao" text,
  "link_gerado" text,
  "link_gerado_por" text,
  "link_gerado_em" timestamp with time zone,
  "enviado_ao_aluno_em" timestamp with time zone,
  "comprovante_anexado_por" text,
  "comprovante_anexado_em" timestamp with time zone,
  "baixa_realizada_por" text,
  "baixa_realizada_em" timestamp with time zone,
  "motivo_divergencia" text,
  "criado_em" timestamp with time zone default now(),
  "operador_solicitante" text,
  "data_vencimento" date,
  "observacao" text,
  "link_pagamento" text,
  "mensagem_pronta" text,
  "adm_responsavel" text,
  "assumido_em" timestamp with time zone,
  "respondido_em" timestamp with time zone,
  "enviado_operador_em" timestamp with time zone,
  "alerta_7min" boolean default false,
  "observacao_comprovante" text,
  "baixa_devolvida_em" timestamp with time zone,
  "baixa_devolvida_por" text,
  "valor_pago" numeric
);

create table public.operador_agenda (
  "id" uuid default gen_random_uuid() primary key,
  "atendimento_id" uuid,
  "aluno_id" text,
  "aluno_nome" text,
  "aluno_cpf" text,
  "operador_email" text,
  "operador_nome" text,
  "retorno_em" timestamp with time zone,
  "titulo" text default 'Retorno de atendimento'::text,
  "tipo" text default 'RETORNO'::text,
  "status" text default 'PENDENTE'::text,
  "observacao" text,
  "concluido_em" timestamp with time zone,
  "criado_em" timestamp with time zone default now(),
  "atualizado_em" timestamp with time zone default now()
);

create table public.parcelas (
  "id" uuid default gen_random_uuid() primary key,
  "acordo_id" uuid,
  "numero" integer default 1,
  "valor" numeric,
  "vencimento" date,
  "status" text default 'A_VENCER'::text,
  "pago_em" timestamp with time zone,
  "confirmado_por_email" text,
  "observacao" text,
  "solicitacao_confirmacao_id" uuid,
  "criado_em" timestamp with time zone default now(),
  "atualizado_em" timestamp with time zone default now(),
  "honorarios" numeric,
  "forma_pagamento" text,
  "is_entrada" boolean default false,
  "boleto" text,
  "titulos_origem" text,
  "boleto_confiavel" boolean default false,
  "renegociada_em" timestamp with time zone,
  "renegociada_no_acordo_id" uuid,
  "origem_baixa" text,
  "origem_baixa_ref" text,
  "origem_baixa_em" timestamp with time zone
);

create table public.reposicao_carteira_fila (
  "id" bigint generated by default as identity primary key,
  "operador_email" text,
  "operador_nome" text,
  "operador_upper" text,
  "tipo" text,
  "caso_origem_id" uuid,
  "criado_em" timestamp with time zone default now(),
  "processado_em" timestamp with time zone,
  "repostos" integer,
  "erro" text
);

create table public.solicitacoes_confirmacao_pagamento (
  "id" uuid default gen_random_uuid() primary key,
  "aluno_id" text,
  "aluno_nome" text,
  "aluno_cpf" text,
  "operador_email" text,
  "operador_nome" text,
  "valor_informado" numeric,
  "motivo" text,
  "status" text default 'AGUARDANDO_CONFIRMACAO'::text,
  "observacao_adm" text,
  "confirmado_por" text,
  "confirmado_em" timestamp with time zone,
  "criado_em" timestamp with time zone default now(),
  "atualizado_em" timestamp with time zone default now(),
  "acordo_id" uuid,
  "parcela_id" uuid,
  "forma_pagamento" text,
  "qtd_parcelas" integer,
  "valor_entrada" numeric,
  "entrada_paga" boolean,
  "titulo_id" uuid,
  "data_pagamento" date,
  "tipo_pagamento" text,
  "comprovante_link_id" uuid,
  "dados_vinculados_em" timestamp with time zone,
  "dados_vinculados_por_email" text,
  "principal_referencia" numeric,
  "juros" numeric,
  "multa" numeric,
  "honorarios" numeric,
  "total_negociado" numeric,
  "composicao_validada_em" timestamp with time zone,
  "composicao_validada_por_email" text,
  "pagamento_id" uuid,
  "origem_divida" text
);

create table public.usuarios (
  "id" uuid default gen_random_uuid() primary key,
  "nome" text,
  "email" text,
  "perfil" text,
  "ativo" boolean default true,
  "created_at" timestamp without time zone default now(),
  "operador_nome" text,
  "operador" text,
  "foto_url" text,
  "apelido" text,
  "aniversario" date,
  "receptivo" boolean default false,
  "pode_gerir_confirmacao_pagamento" boolean default false,
  "pode_alterar_responsavel" boolean default false,
  "deve_trocar_senha" boolean default false,
  "turno" text default 'livre'::text,
  "foto_path" text,
  "nome_exibicao" text
);

-- funcoes reais de producao

CREATE OR REPLACE FUNCTION public.normalizar_status_acionamento(p_status text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  SELECT trim(regexp_replace(
    upper(unaccent(coalesce(p_status, ''))),
    '[_\-]+', ' ', 'g'
  ));
$function$;

CREATE OR REPLACE FUNCTION public.titulo_superado_por_acordo(p_aluno_id uuid, p_vencimento date)
 RETURNS boolean
 LANGUAGE sql
 IMMUTABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  -- Aposentada em 26/08/2026. A mensalidade so sai da conta quando VINCULADA
  -- a um acordo (acordo_titulo_vinculo). Nao existe deducao por data.
  select false;
$function$;

CREATE OR REPLACE FUNCTION public.saldo_titulos_aberto(p_cpf text)
 RETURNS numeric
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select coalesce(sum(t.saldo_corrigido),0)
  from public.acordos_titulos t
  where t.cpf = lpad(regexp_replace(coalesce(p_cpf,''),'\D','','g'),11,'0')
    and coalesce(upper(t.situacao),'') = 'ABERTO'
    and coalesce(lower(t.status),'') <> 'quitada'
    and not exists (select 1 from public.acordo_titulo_vinculo v where v.titulo_id = t.id);
$function$;

CREATE OR REPLACE FUNCTION public.caso_aguarda_confirmacao_financeira(p_aluno_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select p_aluno_id is not null
     and exists (select 1 from public.acordos_titulos t
                  where t.aluno_id = p_aluno_id
                    and upper(coalesce(t.situacao,'')) = 'EM_CONFIRMACAO')
     and coalesce((select sum(coalesce(t.valor_cobranca_ajustado, t.saldo_corrigido, t.valor_em_aberto, t.valor_original, 0))
                     from public.acordos_titulos t
                    where t.aluno_id = p_aluno_id
                      and upper(coalesce(t.situacao,'')) in ('ABERTO','NEGOCIADO')
                      and coalesce(lower(t.status),'') <> 'quitada'
                      and coalesce(t.tipo_boleto,'') <> 'Acordo'
                      and not exists (select 1 from public.acordo_titulo_vinculo v
                                        join public.acordos a on a.id = v.acordo_id
                                       where v.titulo_id = t.id and coalesce(v.ativo, true)
                                         and upper(coalesce(a.status,'')) not in ('CANCELADO','CANCELADA'))), 0) <= 0.005
     and not exists (select 1 from public.parcelas p
                       join public.acordos a on a.id = p.acordo_id
                      where a.aluno_id = p_aluno_id
                        and upper(coalesce(a.status,'')) not in ('CANCELADO','CANCELADA')
                        and upper(coalesce(p.status,'')) not in ('PAGO','CANCELADA','CANCELADO','ESTORNADA','ESTORNADO'));
$function$;

CREATE OR REPLACE FUNCTION public.caso_encerrado_operacional(p_cpf text, p_status_atual text, p_status_acionamento text, p_status_financeiro text, p_status_jornada text)
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare
  bloq text[] := array['CANCELADO','CANCELAMENTO COBRANCA','JURIDICO',
                       'SUSPENSAO COBRANCA','SUSPENSAO DE COBRANCA'];
  -- status_acionamento fala do ACIONAMENTO. 'CANCELADO' aqui e acordo
  -- cancelado, nao cobranca cancelada -- e nao tira ninguem da fila.
  bloq_acion text[] := array['CANCELAMENTO COBRANCA','JURIDICO',
                             'SUSPENSAO COBRANCA','SUSPENSAO DE COBRANCA'];
  quit text[] := array['PAGO','QUITADO','QUITACAO','QUITADO MANUAL','QUITADO AUTOMATICO','SEM SALDO EM ABERTO'];
  nat text := public.normalizar_status_acionamento(p_status_atual);
  nac text := public.normalizar_status_acionamento(p_status_acionamento);
  nfi text := public.normalizar_status_acionamento(p_status_financeiro);
  njo text := public.normalizar_status_acionamento(p_status_jornada);
begin
  if nat = any(bloq) or nac = any(bloq_acion) or nfi = any(bloq) or njo = any(bloq) then return true; end if;
  if nat = 'SEM SALDO EM ABERTO' or nac = 'SEM SALDO EM ABERTO' or njo = 'SEM SALDO EM ABERTO' then return true; end if;
  if nat = 'SALDO ZERO CONFIRMADO' or nac = 'SALDO ZERO CONFIRMADO' or nfi = 'SALDO ZERO CONFIRMADO' or njo = 'SALDO ZERO CONFIRMADO' then return true; end if;
  if (nat = any(quit) or nac = any(quit) or nfi = any(quit) or njo = any(quit)) and public.saldo_titulos_aberto(p_cpf) = 0 then return true; end if;
  return false;
end;
$function$;

CREATE OR REPLACE FUNCTION public.alunos_em_confirmacao_pendente()
 RETURNS TABLE(aluno_id text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT DISTINCT s.aluno_id::text
  FROM public.solicitacoes_confirmacao_pagamento s
  WHERE s.status IN ('AGUARDANDO_CONFIRMACAO', 'PAGAMENTO_RECEBIDO_AGUARDANDO_VINCULO')
    AND s.aluno_id IS NOT NULL;
$function$;

CREATE OR REPLACE FUNCTION public.assumir_caso_livre(p_caso_id uuid)
 RETURNS TABLE(sucesso boolean, mensagem text, caso_liberado uuid)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_email text; v_nome text; v_upper text; v_new record; v_new_saldo numeric; v_count int;
  v_rel record; v_liberado uuid := null;
begin
  v_email := lower(coalesce(auth.jwt() ->> 'email',''));
  if v_email = '' then return query select false,'Usuario nao identificado. Faca login novamente.',null::uuid; return; end if;
  v_nome := public.nome_operador_por_email(v_email);
  if v_nome is null then return query select false,'Operador nao ativo ou nao identificado.',null::uuid; return; end if;
  v_upper := upper(v_nome);
  select c.*, public.saldo_titulos_aberto(c.cpf_limpo) AS _saldo into v_new
    from public.casos c where c.id = p_caso_id for update;
  if not found then return query select false,'Caso nao encontrado.',null::uuid; return; end if;
  if coalesce(v_new.operador_email,'') <> '' then
    return query select false,'Este caso ja foi assumido por outro operador.',null::uuid; return;
  end if;
  if public.caso_protegido_redistribuicao(v_new.cpf_limpo,v_new.status_acionamento,v_new.nao_acionar,v_new.status_financeiro,v_new.valor_pago,v_new.quitado_em,v_new.valor_quitado)
     or public.caso_encerrado_operacional(v_new.cpf_limpo,v_new.status_atual,v_new.status_acionamento,v_new.status_financeiro,v_new.status_jornada)
     or coalesce(v_new._saldo,0) <= 0 then
    return query select false,'Caso nao elegivel (protegido, encerrado ou sem saldo).',null::uuid; return;
  end if;
  v_new_saldo := v_new._saldo;
  v_count := (select count(*) from public.casos where operador_email = v_email
                 and not public.caso_aguarda_confirmacao_financeira(aluno_id));
  if v_count >= 500 then
    select c.id into v_rel from public.casos c
    where c.operador_email = v_email and c.ultima_tabulacao_em is null
      and not public.caso_protegido_redistribuicao(c.cpf_limpo,c.status_acionamento,c.nao_acionar,c.status_financeiro,c.valor_pago,c.quitado_em,c.valor_quitado)
      and not public.caso_encerrado_operacional(c.cpf_limpo,c.status_atual,c.status_acionamento,c.status_financeiro,c.status_jornada)
    order by abs(public.saldo_titulos_aberto(c.cpf_limpo) - v_new_saldo) asc, c.caso_atualizado_em desc nulls last
    limit 1 for update skip locked;
    if v_rel.id is null then
      return query select false,'Carteira cheia (500) e nenhum caso livre para trocar. Assuncao nao realizada.',null::uuid; return;
    end if;
    v_liberado := v_rel.id;
    update public.casos set operador_email=null, operador_nome=null, operador=null where id = v_liberado;
    insert into public.historico_operadores_alunos (chave_unificacao,nome_aluno,cpf_referencia,acao,operador_anterior_nome,operador_anterior_email,observacao,criado_em)
    select chave_unificacao,nome,cpf,'LIBERACAO_TROCA_ASSUMIR',v_nome,v_email,'Liberado por troca ao assumir caso '||p_caso_id::text||'.',now()
    from public.casos where id = v_liberado;
  end if;
  update public.casos set operador_email=v_email, operador_nome=v_nome, operador=v_upper,
    caso_atualizado_por=v_email, caso_atualizado_em=now()
  where id = p_caso_id;
  insert into public.historico_operadores_alunos (chave_unificacao,nome_aluno,cpf_referencia,acao,operador_nome,operador_email,observacao,criado_em)
  select chave_unificacao,nome,cpf,'ASSUMIR_ATENDIMENTO',v_nome,v_email,
    'Assumido caso livre. assumido_por='||v_email||' assumido_em='||now()::text||'. Fidelizacao inicia apenas apos acionamento valido.', now()
  from public.casos where id = p_caso_id;
  if (select count(*) from public.casos where operador_email = v_email
                 and not public.caso_aguarda_confirmacao_financeira(aluno_id)) > 500 then
    raise exception 'ROLLBACK: operador ficaria com mais de 500 casos.';
  end if;
  return query select true, 'Atendimento assumido. Acione dentro do prazo operacional para iniciar a fidelizacao de 10 dias.', v_liberado;
end;
$function$;

CREATE OR REPLACE FUNCTION public.assumir_caso_livre_aluno(p_aluno_id uuid)
 RETURNS TABLE(sucesso boolean, mensagem text, caso_assumido uuid, caso_liberado uuid)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_email text; v_nome text; v_upper text;
  v_new record; v_new_saldo numeric; v_new_faixa int; v_count int; v_rel record;
begin
  v_email := lower(coalesce(auth.jwt() ->> 'email','')); if v_email='' then return query select false,'Usuario nao identificado.',null::uuid,null::uuid; return; end if;
  v_nome := public.nome_operador_por_email(v_email); if v_nome is null then return query select false,'Operador nao ativo.',null::uuid,null::uuid; return; end if;
  v_upper := upper(v_nome);
  select c.*, public.saldo_titulos_aberto(c.cpf_limpo) AS _s into v_new from public.casos c
  where c.aluno_id = p_aluno_id and c.operador_email is null
    and not public.caso_protegido_redistribuicao(c.cpf_limpo,c.status_acionamento,c.nao_acionar,c.status_financeiro,c.valor_pago,c.quitado_em,c.valor_quitado)
    and not public.caso_encerrado_operacional(c.cpf_limpo,c.status_atual,c.status_acionamento,c.status_financeiro,c.status_jornada)
    and public.saldo_titulos_aberto(c.cpf_limpo) > 0
  order by public.saldo_titulos_aberto(c.cpf_limpo) desc limit 1;
  if not found then
    if exists (select 1 from public.casos c where c.aluno_id=p_aluno_id and coalesce(c.operador_email,'')<>'') then
      return query select false,'Este caso ja foi assumido por outro operador.',null::uuid,null::uuid; return; end if;
    return query select false,'Nenhum caso livre elegivel para este aluno.',null::uuid,null::uuid; return;
  end if;
  v_new_saldo := v_new._s;
  v_new_faixa := case when v_new_saldo>10000 then 1 when v_new_saldo>5000 then 2 when v_new_saldo>3000 then 3 else 4 end;
  v_count := public.contar_carteira_ativa(v_email);
  if v_count >= 500 then
    select c.id, c.aluno_id, c.cpf_limpo into v_rel from public.casos c
    where c.operador_email = v_email and c.ultima_tabulacao_em is null
      and not public.caso_protegido_redistribuicao(c.cpf_limpo,c.status_acionamento,c.nao_acionar,c.status_financeiro,c.valor_pago,c.quitado_em,c.valor_quitado)
      and not public.caso_encerrado_operacional(c.cpf_limpo,c.status_atual,c.status_acionamento,c.status_financeiro,c.status_jornada)
    order by (case when (case when public.saldo_titulos_aberto(c.cpf_limpo)>10000 then 1 when public.saldo_titulos_aberto(c.cpf_limpo)>5000 then 2 when public.saldo_titulos_aberto(c.cpf_limpo)>3000 then 3 else 4 end)=v_new_faixa then 0 else 1 end) asc,
             abs(public.saldo_titulos_aberto(c.cpf_limpo)-v_new_saldo) asc, c.caso_atualizado_em desc nulls last limit 1;
    if v_rel.id is null then return query select false,'Carteira cheia (500) e nenhum caso livre para trocar. Assuncao nao realizada.',null::uuid,null::uuid; return; end if;
    update public.casos set operador_email=null, operador_nome=null, operador=null, data_retorno=null, data_retorno_nova=null, hora_retorno=null, proxima_acao_automatica=null where id = v_rel.id;
    update public.operador_agenda set status='CANCELADO_LIBERACAO', atualizado_em=now() where operador_email = v_email and aluno_id = v_rel.aluno_id and coalesce(status,'') not in ('CONCLUIDO','CANCELADO','CANCELADO_LIBERACAO');
    insert into public.historico_operadores_alunos (chave_unificacao,nome_aluno,cpf_referencia,acao,operador_anterior_nome,operador_anterior_email,observacao,criado_em)
    select chave_unificacao,nome,cpf,'LIBERACAO_TROCA_ASSUMIR',v_nome,v_email,'Liberado por troca ao assumir aluno '||p_aluno_id::text||'; agendamento de retorno cancelado. Origem: ASSUMIR_ATENDIMENTO.',now() from public.casos where id = v_rel.id;
  end if;
  update public.casos set operador_email=v_email, operador_nome=v_nome, operador=v_upper, caso_atualizado_por=v_email, caso_atualizado_em=now() where id = v_new.id;
  insert into public.historico_operadores_alunos (chave_unificacao,nome_aluno,cpf_referencia,acao,operador_nome,operador_email,observacao,criado_em)
  select chave_unificacao,nome,cpf,'ASSUMIR_ATENDIMENTO',v_nome,v_email,
    case when v_count>=500 then 'Assumido com troca (liberado '||v_rel.id::text||'). Fidelizacao 10 dias. Origem: ASSUMIR_ATENDIMENTO.' else 'Assumido caso livre. Fidelizacao 10 dias. Origem: ASSUMIR_ATENDIMENTO.' end, now()
  from public.casos where id = v_new.id;
  if public.contar_carteira_ativa(v_email) > 500 then raise exception 'ROLLBACK: operador ficaria com mais de 500 casos ativos.'; end if;
  return query select true, case when v_count>=500 then 'Atendimento assumido (troca): liberado 1 caso e cancelado seu retorno; mantidos 500.' else 'Atendimento assumido.' end,
    v_new.id, (case when v_count>=500 then v_rel.id else null::uuid end);
end;$function$;

CREATE OR REPLACE FUNCTION public.calibragem_e_gestao()
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
begin
  if v_email = '' then return false; end if;
  if v_email in ('amanda.seibel@aelbra.com.br','cobranca04@aelbra.com.br','cobranca07@aelbra.com.br') then return true; end if;
  return false;
end; $function$;

CREATE OR REPLACE FUNCTION public.caso_dentro_prazo_fidelizacao(p_data_ultimo_acionamento date)
 RETURNS boolean
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select p_data_ultimo_acionamento is not null
     and p_data_ultimo_acionamento + 10 >= current_date;
$function$;

CREATE OR REPLACE FUNCTION public.caso_protegido_redistribuicao(p_cpf_limpo text, p_status_acionamento text, p_nao_acionar boolean, p_status_financeiro text DEFAULT NULL::text, p_valor_pago numeric DEFAULT NULL::numeric, p_quitado_em date DEFAULT NULL::date, p_valor_quitado numeric DEFAULT NULL::numeric)
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare
  v_status_norm text := public.normalizar_status_acionamento(p_status_acionamento);
  v_status_fin_norm text := public.normalizar_status_acionamento(p_status_financeiro);
  v_cpf text := lpad(regexp_replace(coalesce(p_cpf_limpo,''), '\D', '', 'g'), 11, '0');
  bloq text[] := array['CANCELADO','CANCELAMENTO COBRANCA','JURIDICO'];
  quit text[] := array['PAGO','QUITADO','QUITACAO','QUITADO MANUAL'];
begin
  if coalesce(p_nao_acionar, false) then return true; end if;

  if v_status_norm = any(bloq) or v_status_fin_norm = any(bloq) then
    return true;
  end if;

  -- Caso cujo unico saldo esta em titulo aguardando a Conferencia Prime: nao
  -- ocupa vaga (teto, reposicao, nivelamento), nao e redistribuido e nao e
  -- solto pela fidelizacao -- o responsavel fica para quando houver decisao.
  -- (o aluno e achado pelo CPF normalizado da ficha -- indice
  -- idx_alunos_cpf_normalizado; o CPF gravado no titulo pode divergir)
  if v_cpf <> '00000000000' and v_cpf <> '' and exists (
       select 1 from public.alunos al
        where lpad(regexp_replace(coalesce(al.cpf, ''), '\D', '', 'g'), 11, '0') = v_cpf
          and exists (select 1 from public.acordos_titulos t
                       where t.aluno_id = al.id
                         and upper(coalesce(t.situacao,'')) = 'EM_CONFIRMACAO')
          and public.caso_aguarda_confirmacao_financeira(al.id)) then
    return true;
  end if;

  if v_cpf = '00000000000' or v_cpf = '' then
    null;
  elsif exists (select 1 from public.acordos a where a.cpf = v_cpf and a.status = 'ATIVO')
     or exists (select 1 from public.baixas_pagamento b where b.aluno_cpf = v_cpf and b.status_baixa = 'AGUARDANDO_BAIXA')
     -- pagamento em transito: protege sempre
     or exists (select 1 from public.links_pagamento l where l.aluno_cpf = v_cpf and l.status = 'AGUARDANDO_BAIXA')
     -- link vivo: protege por um dia
     or exists (select 1 from public.links_pagamento l
                 where l.aluno_cpf = v_cpf
                   and l.status in ('LINK_ENVIADO_AO_ALUNO','LINK_PRONTO_PARA_ENVIO')
                   and coalesce(l.enviado_ao_aluno_em, l.enviado_em, l.criado_em)::date >= current_date - 1)
     or exists (select 1 from public.solicitacoes_confirmacao_pagamento s where s.aluno_cpf = v_cpf and s.status = 'AGUARDANDO_CONFIRMACAO')
  then
    return true;
  end if;

  if (v_status_norm = any(quit) or v_status_fin_norm = any(quit)
      or coalesce(p_valor_pago,0) > 0 or p_quitado_em is not null or coalesce(p_valor_quitado,0) > 0)
     and public.saldo_titulos_aberto(v_cpf) = 0
  then
    return true;
  end if;

  if v_status_norm in (
    'ACORDO FECHADO','ACORDO EM ANDAMENTO','EM NEGOCIACAO',
    'AGUARDANDO PAGAMENTO','AGUARDANDO FINANCEIRO','EMAIL ENVIADO AO FINANCEIRO','E MAIL ENVIADO FINANC',
    'LINK CARTAO ENVIADO','PAGO PARCIAL','VALORES ENVIADOS','PROPOSTA ENVIADA','PROPOSTA DE EXCECAO',
    'TERMO ENVIADO','TERMO RECEBIDO','EM TRATATIVA','RETORNO AGENDADO'
  ) then
    return true;
  end if;

  return false;
end;
$function$;

CREATE OR REPLACE FUNCTION public.caso_reservado_administrativo(p_chave_unificacao text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from public.alunos_unificados au
    where au.chave_unificacao = p_chave_unificacao
      and lower(au.operador_email) = 'cobranca07@aelbra.com.br'
  );
$function$;

CREATE OR REPLACE FUNCTION public.caso_tem_titulo_2026(p_cpf text)
 RETURNS boolean
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from public.acordos_titulos t
    where t.cpf = p_cpf
      and upper(coalesce(t.situacao,'')) = 'ABERTO'
      and extract(year from t.vencimento) = 2026
  );
$function$;

CREATE OR REPLACE FUNCTION public.contar_carteira_ativa(p_email text DEFAULT NULL::text)
 RETURNS integer
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT count(*)::int FROM public.casos c
   WHERE (p_email IS NULL OR c.operador_email = p_email)
     AND (p_email IS NOT NULL OR c.operador_email IS NOT NULL)
     AND c.encerrado_operacional = false
     -- caso que so espera a Conferencia Prime nao ocupa vaga
     AND NOT public.caso_aguarda_confirmacao_financeira(c.aluno_id);
$function$;

CREATE OR REPLACE FUNCTION internal.matricula_em_fidelizacao(p_aluno_id uuid, p_matricula text DEFAULT NULL::text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  WITH alvo AS (
    SELECT p_aluno_id AS aid WHERE p_aluno_id IS NOT NULL
    UNION ALL
    SELECT a.id FROM public.alunos a
    WHERE p_aluno_id IS NULL AND nullif(btrim(p_matricula),'') IS NOT NULL
      AND btrim(a.matricula) = btrim(p_matricula)
      AND (SELECT count(*) FROM public.alunos a2 WHERE btrim(a2.matricula) = btrim(p_matricula)) = 1
  )
  SELECT EXISTS (
    SELECT 1 FROM alvo JOIN public.alunos a ON a.id = alvo.aid
    WHERE a.responsavel_atual_email IS NOT NULL AND a.responsavel_atual_em IS NOT NULL
      AND a.responsavel_atual_em > now() - interval '10 days'
  );
$function$;

CREATE OR REPLACE FUNCTION public.nivelamento_automatico_gestao(p_dias integer DEFAULT 10, p_aplicar boolean DEFAULT true, p_origens text[] DEFAULT ARRAY['amanda.seibel@aelbra.com.br'::text])
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_res jsonb; v_movidos int := 0; v_caso record; v_dest record;
begin
  if not (public.calibragem_e_gestao() or auth.jwt() is null) then
    raise exception 'Sem permissão para nivelar a base da gestão.';
  end if;
  p_dias := greatest(coalesce(p_dias, 10), 0);

  create temp table _eleg on commit drop as
  select c.id caso_id, c.aluno_id, c.chave_unificacao, coalesce(c.nome, c.nome_aluno) nome,
         c.cpf, c.operador_email de_email,
         exists (select 1 from public.acordos a where a.cpf = lpad(regexp_replace(coalesce(c.cpf_limpo,''), '\D','','g'),11,'0') and a.status = 'ATIVO') tem_acordo,
         round(coalesce(s.saldo_total,0),2) valor
    from public.casos c
    join public.calibragem_saldo_aluno s on s.aluno_id = c.aluno_id
   where c.operador_email = any(p_origens)
     and coalesce(s.saldo_total,0) > 0
     and not coalesce(c.nao_acionar, false)
     and not public.caso_encerrado_operacional(c.cpf_limpo, c.status_atual, c.status_acionamento, c.status_financeiro, c.status_jornada)
     and not exists (select 1 from public.links_pagamento l where l.aluno_cpf = lpad(regexp_replace(coalesce(c.cpf_limpo,''),'\D','','g'),11,'0')
                       and l.status in ('AGUARDANDO_BAIXA','LINK_ENVIADO_AO_ALUNO','LINK_PRONTO_PARA_ENVIO'))
     and not exists (select 1 from public.baixas_pagamento b where b.aluno_cpf = lpad(regexp_replace(coalesce(c.cpf_limpo,''),'\D','','g'),11,'0')
                       and b.status_baixa = 'AGUARDANDO_BAIXA')
     and not exists (select 1 from public.solicitacoes_confirmacao_pagamento sc where sc.aluno_cpf = lpad(regexp_replace(coalesce(c.cpf_limpo,''),'\D','','g'),11,'0')
                       and sc.status = 'AGUARDANDO_CONFIRMACAO')
     and (
       exists (select 1 from public.acordos a join public.parcelas pp on pp.acordo_id = a.id
                where a.cpf = lpad(regexp_replace(coalesce(c.cpf_limpo,''),'\D','','g'),11,'0') and a.status = 'ATIVO'
                  and upper(coalesce(pp.status,'')) not in ('PAGO','PAGA','CANCELADA','CANCELADO','ESTORNADA','ESTORNADO')
                  and pp.vencimento < current_date - p_dias)
       or exists (select 1 from public.acordos_titulos t
                   where t.aluno_id = c.aluno_id and upper(coalesce(t.situacao,'')) = 'ABERTO'
                     and lower(coalesce(t.status,'')) = 'em_aberto' and t.acordo_id is null
                     and t.vencimento < current_date - p_dias)
     );

  if not exists (select 1 from _eleg) then
    return jsonb_build_object('dias', p_dias, 'elegiveis', 0, 'movidos', 0,
                              'mensagem', 'Nada vencido além de ' || p_dias || ' dias na base da gestão.');
  end if;

  create temp table _op on commit drop as
  select u.email, u.nome,
         (select count(*) from public.acordos a
            join public.casos c2 on lpad(regexp_replace(coalesce(c2.cpf_limpo,''),'\D','','g'),11,'0') = a.cpf
           where a.status = 'ATIVO' and c2.operador_email = u.email)::int carga_acordo,
         (select count(*) from public.casos c3
            join public.calibragem_saldo_aluno s3 on s3.aluno_id = c3.aluno_id
           where c3.operador_email = u.email and coalesce(s3.saldo_total,0) > 0
             and not public.caso_encerrado_operacional(c3.cpf_limpo, c3.status_atual, c3.status_acionamento, c3.status_financeiro, c3.status_jornada)
             and not public.caso_protegido_redistribuicao(c3.cpf_limpo, c3.status_acionamento, c3.nao_acionar,
                   c3.status_financeiro, c3.valor_pago, c3.quitado_em, c3.valor_quitado))::int carga_caso
    from public.usuarios u
   where u.ativo and u.perfil = 'operador' and not (u.email = any(p_origens));
  if not exists (select 1 from _op) then
    raise exception 'Nenhum operador ativo para receber o nivelamento.';
  end if;

  alter table _eleg add column para_email text, add column para_nome text;

  create temp table _fila on commit drop as
    select caso_id, tem_acordo from _eleg order by tem_acordo desc, valor desc, caso_id;

  for v_caso in select * from _fila loop
    if v_caso.tem_acordo then
      select * into v_dest from _op order by carga_acordo asc, carga_caso asc, email limit 1;
      update _op set carga_acordo = carga_acordo + 1, carga_caso = carga_caso + 1 where email = v_dest.email;
    else
      select * into v_dest from _op order by carga_caso asc, carga_acordo asc, email limit 1;
      update _op set carga_caso = carga_caso + 1 where email = v_dest.email;
    end if;
    update _eleg set para_email = v_dest.email, para_nome = v_dest.nome where caso_id = v_caso.caso_id;
  end loop;

  if p_aplicar then
    perform set_config('calibragem.bypass_teto', 'on', true);
    update public.casos c
       set operador_email = e.para_email, operador_nome = e.para_nome, operador = upper(coalesce(e.para_nome,''))
      from _eleg e where c.id = e.caso_id and e.para_email is not null;
    get diagnostics v_movidos = row_count;

    insert into public.historico_operadores_alunos(aluno_id, chave_unificacao, nome_aluno, cpf_referencia, acao,
      operador_nome, operador_email, operador_anterior_email, observacao, criado_em)
    select e.aluno_id, e.chave_unificacao, e.nome, e.cpf, 'NIVELAMENTO_AUTOMATICO_GESTAO',
      e.para_nome, e.para_email, e.de_email,
      'Débito vencido há mais de ' || p_dias || ' dias na base da gestão: distribuído automaticamente para quem tinha menos.',
      now()
    from _eleg e where e.para_email is not null;
  end if;

  select jsonb_build_object(
    'dias', p_dias, 'aplicado', p_aplicar,
    'elegiveis', (select count(*) from _eleg),
    'movidos', v_movidos,
    'com_acordo', (select count(*) from _eleg where tem_acordo),
    'so_mensalidade', (select count(*) from _eleg where not tem_acordo),
    'valor', (select round(sum(valor),2) from _eleg),
    'destino', (select coalesce(jsonb_agg(jsonb_build_object('operador', para_nome, 'casos', q, 'valor', v) order by q desc),'[]')
                  from (select para_nome, count(*) q, round(sum(valor),2) v from _eleg where para_email is not null group by para_nome) t),
    'carga_depois', (select coalesce(jsonb_agg(jsonb_build_object('operador', nome, 'acordos', carga_acordo, 'casos', carga_caso) order by carga_acordo desc),'[]') from _op)
  ) into v_res;
  return v_res;
end;
$function$;

CREATE OR REPLACE FUNCTION public.nome_operador_por_email(p_email text)
 RETURNS text
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare
  e text;
begin
  e := lower(coalesce(p_email, ''));

  return case e
    when 'amanda.seibel@aelbra.com.br' then 'AMANDA GESTORA'
    when 'cobranca04@aelbra.com.br' then 'FERNANDA'
    when 'cobranca05@aelbra.com.br' then 'LUANA'
    when 'cobranca12@aelbra.com.br' then 'DIEGO'
    when 'cobranca13@aelbra.com.br' then 'RAFAELLA'
    when 'cobranca07@aelbra.com.br' then 'AMANDA ADM'
    when 'cobranca11@aelbra.com.br' then 'ALLAN'
    when 'cobranca06@aelbra.com.br' then 'MAURICIO'
    when 'cobranca03@aelbra.com.br' then 'OLGA'
    when 'cobranca10@aelbra.com.br' then 'JOAO'
    when 'cobranca08@aelbra.com.br' then 'NATALY'
    else upper(split_part(e, '@', 1))
  end;
end;
$function$;

CREATE OR REPLACE FUNCTION public.reposicao_carteira_processar(p_max_pedidos integer DEFAULT 5)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
 SET statement_timeout TO '300s'
AS $function$
declare
  v_meta int := 500;
  ped record;
  caso_rec record;
  v_qtd_ativa int;
  v_faltam int;
  v_repostos int;
  v_media_geral numeric;
  v_total_pedidos int := 0;
  v_total_repostos int := 0;
  v_sob_carga boolean := false;
begin
  begin
    v_sob_carga := coalesce((public.sistema_sob_carga() ->> 'sob_carga')::boolean, false);
  exception when others then
    v_sob_carga := false;
  end;
  if v_sob_carga then
    return jsonb_build_object('ok', true, 'pulado', 'sistema_sob_carga');
  end if;

  for ped in
    select f.*
      from public.reposicao_carteira_fila f
     where f.processado_em is null
     order by f.criado_em
     limit p_max_pedidos
       for update skip locked
  loop
    v_total_pedidos := v_total_pedidos + 1;
    v_repostos := 0;

    if not exists (select 1 from public.usuarios u where u.email = ped.operador_email and u.perfil = 'operador' and u.ativo = true) then
      update public.reposicao_carteira_fila
         set processado_em = now(), repostos = 0, erro = 'operador nao esta mais ativo'
       where id = ped.id;
      continue;
    end if;

    select count(*) into v_qtd_ativa
      from public.casos c
     where c.operador_email = ped.operador_email
       and not public.caso_protegido_redistribuicao(c.cpf_limpo, c.status_acionamento, c.nao_acionar, c.status_financeiro, c.valor_pago, c.quitado_em, c.valor_quitado);

    v_faltam := v_meta - v_qtd_ativa;

    if v_faltam > 0 then
      if ped.tipo = 'QUITADO' then
        select round(avg(coalesce(total_em_aberto,0))::numeric,2) into v_media_geral
          from public.casos where operador_email is not null and operador_email <> 'amanda.seibel@aelbra.com.br';

        for caso_rec in
          select id, chave_unificacao, nome, cpf, total_em_aberto
            from public.casos
           where operador_email is null
             and not public.caso_protegido_redistribuicao(cpf_limpo, status_acionamento, nao_acionar, status_financeiro, valor_pago, quitado_em, valor_quitado)
             and not public.caso_reservado_administrativo(chave_unificacao)
             and coalesce(total_em_aberto, 0) > 0
           order by public.caso_tem_titulo_2026(cpf_limpo) desc,
                    abs(coalesce(total_em_aberto,0) - coalesce(v_media_geral, coalesce(total_em_aberto,0))) asc
           limit v_faltam
        loop
          update public.casos
             set operador_email = ped.operador_email, operador_nome = ped.operador_nome, operador = ped.operador_upper,
                 caso_atualizado_por = 'sistema_reposicao_automatica_nivelada', caso_atualizado_em = now()
           where id = caso_rec.id;

          insert into public.historico_operadores_alunos (
            chave_unificacao, nome_aluno, cpf_referencia, acao,
            operador_nome, operador_email, observacao, criado_em
          ) values (
            caso_rec.chave_unificacao, caso_rec.nome, caso_rec.cpf, 'REPOSICAO_AUTOMATICA_VAGA',
            ped.operador_nome, ped.operador_email,
            'Reposicao nivelada (2026 primeiro, valor perto da media geral ' || coalesce(v_media_geral::text,'-') || ', caso anterior QUITADO) por ' || coalesce(ped.operador_nome, ped.operador_email), now()
          );
          v_repostos := v_repostos + 1;
        end loop;
      else
        for caso_rec in
          select id, chave_unificacao, nome, cpf, total_em_aberto
            from public.casos
           where operador_email is null
             and not public.caso_protegido_redistribuicao(cpf_limpo, status_acionamento, nao_acionar, status_financeiro, valor_pago, quitado_em, valor_quitado)
             and not public.caso_reservado_administrativo(chave_unificacao)
           order by public.caso_tem_titulo_2026(cpf_limpo) desc, (status_acionamento is null) desc, random()
           limit v_faltam
        loop
          update public.casos
             set operador_email = ped.operador_email, operador_nome = ped.operador_nome, operador = ped.operador_upper,
                 caso_atualizado_por = 'sistema_reposicao_automatica', caso_atualizado_em = now()
           where id = caso_rec.id;

          insert into public.historico_operadores_alunos (
            chave_unificacao, nome_aluno, cpf_referencia, acao,
            operador_nome, operador_email, observacao, criado_em
          ) values (
            caso_rec.chave_unificacao, caso_rec.nome, caso_rec.cpf, 'REPOSICAO_AUTOMATICA_VAGA',
            ped.operador_nome, ped.operador_email,
            'Reposicao (2026 primeiro, caso anterior foi ' || ped.tipo || ') por ' || coalesce(ped.operador_nome, ped.operador_email), now()
          );
          v_repostos := v_repostos + 1;
        end loop;
      end if;
    end if;

    update public.reposicao_carteira_fila
       set processado_em = now(), repostos = v_repostos
     where id = ped.id;

    v_total_repostos := v_total_repostos + v_repostos;
  end loop;

  return jsonb_build_object('ok', true, 'pedidos', v_total_pedidos, 'repostos', v_total_repostos);
end;
$function$;

-- STUB de infraestrutura (o real le pg_stat_activity)
create or replace function public.sistema_sob_carga() returns jsonb language sql stable as $$ select jsonb_build_object('sob_carga', false) $$;

CREATE OR REPLACE FUNCTION public.tipo_fechamento_caso(p_cpf_limpo text, p_status_acionamento text, p_status_financeiro text, p_quitado_em date, p_valor_quitado numeric)
 RETURNS text
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
DECLARE
  v_status_norm text := public.normalizar_status_acionamento(p_status_acionamento);
  v_status_fin_norm text := public.normalizar_status_acionamento(p_status_financeiro);
  v_cpf text := lpad(regexp_replace(coalesce(p_cpf_limpo,''), '\D', '', 'g'), 11, '0');
BEGIN
  IF v_status_norm = 'QUITADO'
     OR v_status_fin_norm IN ('PAGO', 'QUITADO')
     OR p_quitado_em IS NOT NULL
     OR coalesce(p_valor_quitado, 0) > 0
  THEN
    RETURN 'QUITADO';
  END IF;

  IF v_cpf <> '' AND v_cpf <> '00000000000'
     AND EXISTS (SELECT 1 FROM public.acordos a WHERE a.cpf = v_cpf AND a.status = 'QUITADO')
  THEN
    RETURN 'QUITADO';
  END IF;

  RETURN 'OUTRO'; -- acordo parcelado ativo, negociação, proposta, termo etc.
END;
$function$;

CREATE OR REPLACE FUNCTION public.trg_repor_caso_operador()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_email text := NEW.operador_email;
  v_nome  text := NEW.operador_nome;
  v_tipo  text;
begin
  if v_email is null then
    return NEW;
  end if;

  if not exists (select 1 from public.usuarios u where u.email = v_email and u.perfil = 'operador' and u.ativo = true) then
    return NEW;
  end if;

  if public.caso_protegido_redistribuicao(OLD.cpf_limpo, OLD.status_acionamento, OLD.nao_acionar, OLD.status_financeiro, OLD.valor_pago, OLD.quitado_em, OLD.valor_quitado) then
    return NEW;
  end if;

  if not public.caso_protegido_redistribuicao(NEW.cpf_limpo, NEW.status_acionamento, NEW.nao_acionar, NEW.status_financeiro, NEW.valor_pago, NEW.quitado_em, NEW.valor_quitado) then
    return NEW;
  end if;

  v_tipo := public.tipo_fechamento_caso(NEW.cpf_limpo, NEW.status_acionamento, NEW.status_financeiro, NEW.quitado_em, NEW.valor_quitado);

  update public.casos
     set operador_email = null, operador_nome = null, operador = null
   where id = NEW.id;

  insert into public.historico_operadores_alunos (
    chave_unificacao, nome_aluno, cpf_referencia, acao,
    operador_anterior_nome, operador_anterior_email, observacao, criado_em
  ) values (
    NEW.chave_unificacao, NEW.nome, NEW.cpf, 'LIBERACAO_AUTOMATICA_CASO_FECHADO',
    v_nome, v_email,
    'Caso fechado (' || v_tipo || ', status: ' || coalesce(NEW.status_acionamento,'-') || ') -- liberado automaticamente', now()
  );

  insert into public.reposicao_carteira_fila (operador_email, operador_nome, operador_upper, tipo, caso_origem_id)
  values (v_email, v_nome, NEW.operador, v_tipo, NEW.id);

  return NEW;
end;
$function$;

CREATE OR REPLACE FUNCTION public.usuario_e_gestao()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select lower(coalesce(auth.jwt()->>'email','')) in (
    'amanda.seibel@aelbra.com.br',
    'cobranca04@aelbra.com.br',
    'cobranca07@aelbra.com.br'
  );
$function$;

-- view real

create or replace view public.calibragem_saldo_aluno as
WITH tit AS (
         SELECT t.aluno_id,
            t.cpf,
            sum(COALESCE(t.saldo_corrigido, t.valor_em_aberto, t.valor_original, (0)::numeric)) AS saldo_mensalidade,
            count(*) AS qtd_titulos_abertos,
            min(t.vencimento) AS venc_min,
            max(t.vencimento) AS venc_max
           FROM acordos_titulos t
          WHERE ((upper(COALESCE(t.situacao, ''::text)) = 'ABERTO'::text) AND (lower(COALESCE(t.status, ''::text)) = 'em_aberto'::text) AND (t.acordo_id IS NULL) AND (NOT (EXISTS ( SELECT 1
                   FROM acordo_titulo_vinculo v
                  WHERE ((v.titulo_id = t.id) AND COALESCE(v.ativo, true))))) AND (NOT titulo_superado_por_acordo(t.aluno_id, t.vencimento)))
          GROUP BY t.aluno_id, t.cpf
        ), par AS (
         SELECT a.aluno_id,
            sum(COALESCE(p.valor, (0)::numeric)) AS saldo_acordo,
            count(*) AS qtd_parcelas_abertas
           FROM (parcelas p
             JOIN acordos a ON ((a.id = p.acordo_id)))
          WHERE ((lower(COALESCE(a.status, ''::text)) <> ALL (ARRAY['cancelado'::text, 'cancelada'::text])) AND (upper(COALESCE(p.status, ''::text)) <> ALL (ARRAY['PAGO'::text, 'PAGA'::text, 'CANCELADA'::text, 'CANCELADO'::text, 'ESTORNADA'::text, 'ESTORNADO'::text])))
          GROUP BY a.aluno_id
        )
 SELECT COALESCE(tit.aluno_id, par.aluno_id) AS aluno_id,
    tit.cpf,
    COALESCE(tit.saldo_mensalidade, (0)::numeric) AS saldo_mensalidade,
    COALESCE(par.saldo_acordo, (0)::numeric) AS saldo_acordo,
    (COALESCE(tit.saldo_mensalidade, (0)::numeric) + COALESCE(par.saldo_acordo, (0)::numeric)) AS saldo_total,
    COALESCE(tit.qtd_titulos_abertos, (0)::bigint) AS qtd_titulos_abertos,
    COALESCE(par.qtd_parcelas_abertas, (0)::bigint) AS qtd_parcelas_abertas,
    tit.venc_min,
    tit.venc_max
   FROM (tit
     FULL JOIN par ON ((par.aluno_id = tit.aluno_id)));

CREATE OR REPLACE FUNCTION public._aluno_aguardando_baixa_ao_confirmar()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if upper(coalesce(new.status,'')) = 'AGUARDANDO_CONFIRMACAO' and new.aluno_id is not null then
    update public.alunos set
      status_jornada = 'AGUARDANDO_BAIXA',
      status_atual = 'AGUARDANDO_BAIXA',
      status_acionamento = 'Aguardando confirmação de pagamento',
      data_ultimo_acionamento = now()
    where id::text = new.aluno_id::text
      and status_jornada not in ('QUITADO','QUITADO_MANUAL','BAIXA_REALIZADA','AGUARDANDO_BAIXA');

    update public.casos c
       set criticidade = 'NORMAL',
           status_acionamento = 'Aguardando confirmação de pagamento'
     where c.aluno_id::text = new.aluno_id::text
       and c.quitado_em is null
       and not public.caso_encerrado_operacional(c.cpf, c.status_atual, c.status_acionamento, c.status_financeiro, c.status_jornada);
  end if;
  return new;
end;
$function$;

-- gatilhos reais de producao (pg_get_triggerdef)
CREATE TRIGGER trigger_repor_caso_operador AFTER UPDATE ON public.casos FOR EACH ROW WHEN (((new.operador_email IS NOT NULL) AND (new.operador_email = old.operador_email))) EXECUTE FUNCTION trg_repor_caso_operador();
CREATE TRIGGER trg_aluno_aguardando_baixa AFTER INSERT ON public.solicitacoes_confirmacao_pagamento FOR EACH ROW EXECUTE FUNCTION _aluno_aguardando_baixa_ao_confirmar();
