// Estilo compartilhado das duas filas de confirmacao (acordos e pagamentos):
// as telas tem que ser a MESMA tela com conteudos diferentes, entao o padrao
// visual mora aqui, num lugar so, em vez de ser copiado de uma pra outra.
export const S = {
  wrap: { padding: "28px 30px 40px", fontFamily: "'Inter', system-ui, sans-serif", color: "#0f172a", background: "#f4f6fa", minHeight: "100%" },
  topo: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 16, flexWrap: "wrap", marginBottom: 14 },
  titulo: { margin: 0, fontFamily: "'Sora', Inter, sans-serif", fontSize: 24, fontWeight: 800, color: "#0d1321", letterSpacing: "-0.03em" },
  sub: { margin: "5px 0 0", color: "#64748b", fontSize: 13 },
  btnGhost: { background: "#1e40af", color: "#fff", border: "none", borderRadius: 10, padding: "10px 18px", fontWeight: 700, fontSize: 13, cursor: "pointer" },
  barra: { display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap", marginBottom: 14 },
  select: { border: "1px solid #cbd5e1", borderRadius: 10, padding: "8px 12px", fontSize: 13, background: "#fff", color: "#0f172a" },
  input: { border: "1px solid #cbd5e1", borderRadius: 10, padding: "8px 12px", fontSize: 13, background: "#fff", color: "#0f172a", minWidth: 240, outline: "none" },
  contadores: { display: "flex", gap: 8, alignItems: "center", marginLeft: "auto", flexWrap: "wrap" },
  contadorAlunos: { fontSize: 12, fontWeight: 800, color: "#3730a3", background: "#eef2ff", border: "1px solid #c7d2fe", borderRadius: 999, padding: "4px 12px" },
  contadorAcordos: { fontSize: 12, fontWeight: 800, color: "#166534", background: "#f0fdf4", border: "1px solid #bbf7d0", borderRadius: 999, padding: "4px 12px" },
  contadorValor: { fontSize: 12, fontWeight: 800, color: "#334155", background: "#f1f5f9", border: "1px solid #e2e8f0", borderRadius: 999, padding: "4px 12px" },
  erroBox: { background: "#fef2f2", color: "#991b1b", border: "1px solid #fecaca", borderRadius: 10, padding: "10px 14px", fontSize: 13, fontWeight: 600, marginBottom: 14 },
  muted: { color: "#64748b", fontSize: 14 },
  cards: { display: "flex", flexDirection: "column", gap: 14 },
  card: { background: "#fff", borderRadius: 12, border: "1px solid #e6eaf0", overflow: "hidden", boxShadow: "0 1px 2px rgba(15,23,42,0.04)" },
  cardHead: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, flexWrap: "wrap", padding: "12px 16px", borderBottom: "1px solid #eef1f6", background: "#f8fafc" },
  cardHeadInfo: { display: "flex", alignItems: "baseline", gap: 12, flexWrap: "wrap" },
  cardHeadDir: { display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" },
  cardNome: { fontFamily: "'Sora', Inter, sans-serif", fontSize: 15, fontWeight: 800, color: "#0d1321" },
  cardCpf: { fontSize: 12.5, color: "#64748b", fontWeight: 600 },
  cardUnidade: { fontSize: 12, color: "#8a93a3" },
  cardResumo: { fontSize: 12.5, color: "#475569", fontWeight: 700 },
  tabela: { width: "100%", borderCollapse: "collapse", fontSize: 13, background: "#fff" },
  th: { textAlign: "left", padding: "9px 14px", color: "#8a93a3", fontSize: 10.5, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", background: "#fff", borderBottom: "1px solid #eef1f6" },
  thNum: { textAlign: "right", padding: "9px 14px", color: "#8a93a3", fontSize: 10.5, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", background: "#fff", borderBottom: "1px solid #eef1f6" },
  td: { padding: "10px 14px", borderBottom: "1px solid #f4f6f9", color: "#344054" },
  tdNum: { padding: "10px 14px", borderBottom: "1px solid #f4f6f9", textAlign: "right", fontWeight: 700, color: "#101828" },
  acoes: { display: "flex", gap: 8, alignItems: "center", justifyContent: "flex-end" },
  respCell: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" },
  resp: { fontSize: 12.5, fontWeight: 600, color: "#334155" },
  respVazio: { fontSize: 12.5, fontWeight: 600, color: "#94a3b8", fontStyle: "italic" },
  respNaoVinc: { fontSize: 12.5, fontWeight: 700, color: "#b45309", fontStyle: "italic" },
  btnVinc: { background: "#eef2ff", color: "#3730a3", border: "1px solid #c7d2fe", borderRadius: 8, padding: "4px 10px", fontSize: 11.5, fontWeight: 700, cursor: "pointer" },
  vincBox: { background: "#fff", borderRadius: 14, width: "min(520px, 96vw)", maxHeight: "94vh", display: "flex", flexDirection: "column", overflow: "hidden", boxShadow: "0 20px 60px rgba(0,0,0,0.35)" },
  vincCorpo: { padding: "16px 18px", display: "flex", flexDirection: "column", gap: 10, overflow: "auto" },
  vincSub: { margin: 0, fontSize: 13, color: "#475569" },
  vincLabel: { fontSize: 12, fontWeight: 700, color: "#334155", marginTop: 4 },
  vincLinha: { display: "flex", gap: 8, alignItems: "center" },
  vincAchado: { border: "1px solid #e2e8f0", background: "#f8fafc", borderRadius: 10, padding: "10px 12px", fontSize: 13, color: "#0f172a" },
  vincTextarea: { border: "1px solid #cbd5e1", borderRadius: 10, padding: "8px 12px", fontSize: 13, background: "#fff", color: "#0f172a", resize: "vertical", fontFamily: "inherit" },
  vincAcoes: { display: "flex", justifyContent: "flex-end", gap: 10, marginTop: 6 },
  btnGhostClaro: { background: "#f1f5f9", color: "#334155", border: "1px solid #e2e8f0", borderRadius: 10, padding: "9px 16px", fontWeight: 700, fontSize: 13, cursor: "pointer" },
  chip: { fontSize: 11, fontWeight: 700, borderRadius: 999, padding: "2px 10px", whiteSpace: "nowrap" },
  chipPend: { background: "#fffbeb", color: "#92400e", border: "1px solid #fde68a" },
  chipOk: { background: "#f0fdf4", color: "#166534", border: "1px solid #86efac" },
  chipZero: { background: "#f1f5f9", border: "1px solid #e2e8f0", color: "#475569" },
  chipRej: { background: "#fef2f2", color: "#991b1b", border: "1px solid #fecaca" },
  btnConf: { background: "#15803d", color: "#fff", border: "none", borderRadius: 8, padding: "6px 14px", fontSize: 12.5, fontWeight: 700, cursor: "pointer" },
  btnRej: { background: "#b91c1c", color: "#fff", border: "none", borderRadius: 8, padding: "6px 14px", fontSize: 12.5, fontWeight: 700, cursor: "pointer" },
  btnMini: { background: "transparent", color: "#2563eb", border: "none", fontSize: 12, fontWeight: 700, cursor: "pointer" },
  btnBusy: { opacity: 0.55, cursor: "not-allowed" },
  btnFicha: { background: "#eef2ff", color: "#3730a3", border: "1px solid #c7d2fe", borderRadius: 8, padding: "6px 12px", fontSize: 12.5, fontWeight: 700, cursor: "pointer" },
  modalOverlay: { position: "fixed", inset: 0, background: "rgba(15,23,42,0.55)", display: "flex", alignItems: "flex-start", justifyContent: "center", padding: "3vh 2vw", zIndex: 1000 },
  modalBox: { background: "#fff", borderRadius: 16, width: "min(1100px, 96vw)", maxHeight: "94vh", display: "flex", flexDirection: "column", overflow: "hidden", boxShadow: "0 20px 60px rgba(0,0,0,0.35)" },
  modalTopo: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "12px 16px", borderBottom: "1px solid #e6eaf0", background: "#f8fafc" },
  modalTitulo: { fontFamily: "'Sora', Inter, sans-serif", fontSize: 15, fontWeight: 800, color: "#0d1321" },
  modalFechar: { background: "#0f172a", color: "#fff", border: "none", borderRadius: 8, padding: "7px 14px", fontSize: 12.5, fontWeight: 700, cursor: "pointer" },
  modalConteudo: { overflow: "auto", flex: 1 },
};
