// Estilo compartilhado das duas filas de confirmacao (acordos e pagamentos):
// as telas tem que ser a MESMA tela com conteudos diferentes, entao o padrao
// visual mora aqui, num lugar so, em vez de ser copiado de uma pra outra.
export const S = {
  wrap: { padding: "28px 30px 40px", fontFamily: "'Inter', system-ui, sans-serif", color: "var(--rv-tinta)", background: "var(--rv-fundo)", minHeight: "100%" },
  topo: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 16, flexWrap: "wrap", marginBottom: 14 },
  titulo: { margin: 0, fontFamily: "'Sora', Inter, sans-serif", fontSize: 24, fontWeight: 800, color: "var(--rv-tinta)", letterSpacing: "-0.03em" },
  sub: { margin: "5px 0 0", color: "var(--rv-texto-suave)", fontSize: 13 },
  btnGhost: { background: "#1e40af", color: "#fff", border: "none", borderRadius: 10, padding: "10px 18px", fontWeight: 700, fontSize: 13, cursor: "pointer" },
  barra: { display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap", marginBottom: 14 },
  select: { border: "1px solid var(--rv-borda-forte)", borderRadius: 10, padding: "8px 12px", fontSize: 13, background: "var(--rv-superficie)", color: "var(--rv-tinta)" },
  input: { border: "1px solid var(--rv-borda-forte)", borderRadius: 10, padding: "8px 12px", fontSize: 13, background: "var(--rv-superficie)", color: "var(--rv-tinta)", minWidth: 240, outline: "none" },
  contadores: { display: "flex", gap: 8, alignItems: "center", marginLeft: "auto", flexWrap: "wrap" },
  contadorAlunos: { fontSize: 12, fontWeight: 800, color: "var(--rv-roxo-texto)", background: "var(--rv-roxo-fundo)", border: "1px solid var(--rv-roxo-borda)", borderRadius: 999, padding: "4px 12px" },
  contadorAcordos: { fontSize: 12, fontWeight: 800, color: "var(--rv-verde-ok-texto)", background: "var(--rv-verde-ok-fundo)", border: "1px solid var(--rv-verde-ok-borda)", borderRadius: 999, padding: "4px 12px" },
  contadorValor: { fontSize: 12, fontWeight: 800, color: "var(--rv-texto-forte)", background: "var(--rv-fundo-suave)", border: "1px solid var(--rv-borda)", borderRadius: 999, padding: "4px 12px" },
  erroBox: { background: "var(--rv-vermelho-fundo)", color: "var(--rv-vermelho-texto)", border: "1px solid var(--rv-vermelho-borda)", borderRadius: 10, padding: "10px 14px", fontSize: 13, fontWeight: 600, marginBottom: 14 },
  muted: { color: "var(--rv-texto-suave)", fontSize: 14 },
  cards: { display: "flex", flexDirection: "column", gap: 14 },
  card: { background: "var(--rv-superficie)", borderRadius: 12, border: "1px solid var(--rv-borda)", overflow: "hidden", boxShadow: "0 1px 2px rgba(15,23,42,0.04)" },
  cardHead: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, flexWrap: "wrap", padding: "12px 16px", borderBottom: "1px solid var(--rv-borda-suave)", background: "var(--rv-fundo-cartao)" },
  cardHeadInfo: { display: "flex", alignItems: "baseline", gap: 12, flexWrap: "wrap" },
  cardHeadDir: { display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" },
  cardNome: { fontFamily: "'Sora', Inter, sans-serif", fontSize: 15, fontWeight: 800, color: "var(--rv-tinta)" },
  cardCpf: { fontSize: 12.5, color: "var(--rv-texto-suave)", fontWeight: 600 },
  cardUnidade: { fontSize: 12, color: "var(--rv-texto-fraco)" },
  cardResumo: { fontSize: 12.5, color: "var(--rv-texto)", fontWeight: 700 },
  tabela: { width: "100%", borderCollapse: "collapse", fontSize: 13, background: "var(--rv-superficie)" },
  th: { textAlign: "left", padding: "9px 14px", color: "var(--rv-texto-fraco)", fontSize: 10.5, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", background: "var(--rv-superficie)", borderBottom: "1px solid var(--rv-borda-suave)" },
  thNum: { textAlign: "right", padding: "9px 14px", color: "var(--rv-texto-fraco)", fontSize: 10.5, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", background: "var(--rv-superficie)", borderBottom: "1px solid var(--rv-borda-suave)" },
  td: { padding: "10px 14px", borderBottom: "1px solid var(--rv-borda-suave)", color: "var(--rv-texto-forte)" },
  tdNum: { padding: "10px 14px", borderBottom: "1px solid var(--rv-borda-suave)", textAlign: "right", fontWeight: 700, color: "var(--rv-tinta)" },
  acoes: { display: "flex", gap: 8, alignItems: "center", justifyContent: "flex-end" },
  respCell: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" },
  resp: { fontSize: 12.5, fontWeight: 600, color: "var(--rv-texto-forte)" },
  respVazio: { fontSize: 12.5, fontWeight: 600, color: "var(--rv-texto-fraco)", fontStyle: "italic" },
  respNaoVinc: { fontSize: 12.5, fontWeight: 700, color: "var(--rv-ambar-texto)", fontStyle: "italic" },
  btnVinc: { background: "var(--rv-roxo-fundo)", color: "var(--rv-roxo-texto)", border: "1px solid var(--rv-roxo-borda)", borderRadius: 8, padding: "4px 10px", fontSize: 11.5, fontWeight: 700, cursor: "pointer" },
  vincBox: { background: "var(--rv-superficie)", borderRadius: 14, width: "min(520px, 96vw)", maxHeight: "94vh", display: "flex", flexDirection: "column", overflow: "hidden", boxShadow: "0 20px 60px rgba(0,0,0,0.35)" },
  vincCorpo: { padding: "16px 18px", display: "flex", flexDirection: "column", gap: 10, overflow: "auto" },
  vincSub: { margin: 0, fontSize: 13, color: "var(--rv-texto)" },
  vincLabel: { fontSize: 12, fontWeight: 700, color: "var(--rv-texto-forte)", marginTop: 4 },
  vincLinha: { display: "flex", gap: 8, alignItems: "center" },
  vincAchado: { border: "1px solid var(--rv-borda)", background: "var(--rv-fundo-cartao)", borderRadius: 10, padding: "10px 12px", fontSize: 13, color: "var(--rv-tinta)" },
  vincTextarea: { border: "1px solid var(--rv-borda-forte)", borderRadius: 10, padding: "8px 12px", fontSize: 13, background: "var(--rv-superficie)", color: "var(--rv-tinta)", resize: "vertical", fontFamily: "inherit" },
  vincAcoes: { display: "flex", justifyContent: "flex-end", gap: 10, marginTop: 6 },
  btnGhostClaro: { background: "var(--rv-fundo-suave)", color: "var(--rv-texto-forte)", border: "1px solid var(--rv-borda)", borderRadius: 10, padding: "9px 16px", fontWeight: 700, fontSize: 13, cursor: "pointer" },
  chip: { fontSize: 11, fontWeight: 700, borderRadius: 999, padding: "2px 10px", whiteSpace: "nowrap" },
  chipPend: { background: "var(--rv-ambar-fundo)", color: "var(--rv-ambar-texto)", border: "1px solid var(--rv-ambar-borda)" },
  chipOk: { background: "var(--rv-verde-ok-fundo)", color: "var(--rv-verde-ok-texto)", border: "1px solid var(--rv-verde-ok-borda)" },
  chipZero: { background: "var(--rv-fundo-suave)", border: "1px solid var(--rv-borda)", color: "var(--rv-texto)" },
  chipRej: { background: "var(--rv-vermelho-fundo)", color: "var(--rv-vermelho-texto)", border: "1px solid var(--rv-vermelho-borda)" },
  btnConf: { background: "#15803d", color: "#fff", border: "none", borderRadius: 8, padding: "6px 14px", fontSize: 12.5, fontWeight: 700, cursor: "pointer" },
  btnRej: { background: "#b91c1c", color: "#fff", border: "none", borderRadius: 8, padding: "6px 14px", fontSize: 12.5, fontWeight: 700, cursor: "pointer" },
  btnMini: { background: "transparent", color: "var(--rv-azul)", border: "none", fontSize: 12, fontWeight: 700, cursor: "pointer" },
  btnBusy: { opacity: 0.55, cursor: "not-allowed" },
  btnFicha: { background: "var(--rv-roxo-fundo)", color: "var(--rv-roxo-texto)", border: "1px solid var(--rv-roxo-borda)", borderRadius: 8, padding: "6px 12px", fontSize: 12.5, fontWeight: 700, cursor: "pointer" },
  modalOverlay: { position: "fixed", inset: 0, background: "rgba(15,23,42,0.55)", display: "flex", alignItems: "flex-start", justifyContent: "center", padding: "3vh 2vw", zIndex: 1000 },
  modalBox: { background: "var(--rv-superficie)", borderRadius: 16, width: "min(1100px, 96vw)", maxHeight: "94vh", display: "flex", flexDirection: "column", overflow: "hidden", boxShadow: "0 20px 60px rgba(0,0,0,0.35)" },
  modalTopo: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "12px 16px", borderBottom: "1px solid var(--rv-borda)", background: "var(--rv-fundo-cartao)" },
  modalTitulo: { fontFamily: "'Sora', Inter, sans-serif", fontSize: 15, fontWeight: 800, color: "var(--rv-tinta)" },
  modalFechar: { background: "var(--rv-botao-escuro)", color: "#fff", border: "none", borderRadius: 8, padding: "7px 14px", fontSize: 12.5, fontWeight: 700, cursor: "pointer" },
  modalConteudo: { overflow: "auto", flex: 1 },
};
