-- =============================================================================
-- TV ReATIVA — ETAPA 3: regras detalhadas das telas ativas
-- =============================================================================
-- Mantém a arquitetura das Etapas 1+2 (snapshot + TV só lê). TODOS os cálculos
-- novos acontecem AQUI, no gerador do snapshot (disparado pelo botão "Atualizar
-- projeção"). A TV apenas exibe os campos já prontos do payload.
--
-- Adiciona ao payload: hoje, mes, metas[], rankings, julho_historico, avisos.
-- Novas estruturas: colunas de janela/prioridade em tv_mensagem_especial;
-- tabela tv_config (flag do "Julho Histórico"); tabela tv_aniversariantes
-- (fonte curada pela gestão, substitui usuarios.aniversario na TV).
--
-- Base de "pagamento confirmado" = tabela public.pagamentos (só contém pagamentos
-- efetivados; os aguardando confirmação ficam fora dela). id uuid = 1 lançamento.
-- PRIVACIDADE: nenhum campo de aluno (nome/CPF) entra no payload.
-- =============================================================================

-- 0) Avisos: janela de vigência + prioridade -------------------------------
alter table public.tv_mensagem_especial add column if not exists data_inicial date;
alter table public.tv_mensagem_especial add column if not exists data_final   date;
alter table public.tv_mensagem_especial add column if not exists prioridade    integer not null default 0;

-- 0b) A mensagem seed "BORA TIME" é de META, não um aviso genérico. A regra da
--     Etapa 3 proíbe usar mensagem de meta como aviso — desativa só o seed
--     intocado (a gestão cria avisos reais pelo editor).
update public.tv_mensagem_especial set ativo = false
 where atualizado_por = 'seed' and coalesce(data_inicial, data_final) is null;

-- 1) Config chave-valor (ativa/desativa telas especiais, ex.: Julho Histórico)
create table if not exists public.tv_config (
  chave        text primary key,
  ativo        boolean not null default false,
  valor        jsonb,
  atualizado_em timestamptz not null default now()
);
alter table public.tv_config enable row level security;
drop policy if exists tv_config_sel on public.tv_config;
create policy tv_config_sel on public.tv_config for select to authenticated using (true);
drop policy if exists tv_config_wr on public.tv_config;
create policy tv_config_wr on public.tv_config for all to authenticated
  using (lower(auth.email()) in ('amanda.seibel@aelbra.com.br','cobranca04@aelbra.com.br'))
  with check (lower(auth.email()) in ('amanda.seibel@aelbra.com.br','cobranca04@aelbra.com.br'));

-- Seed do Julho Histórico (ativo; textos default). Desative pela gestão em agosto.
insert into public.tv_config (chave, ativo, valor)
select 'julho_historico', true, jsonb_build_object(
  'titulo','Julho Histórico',
  'texto_principal','Em julho, a operação ReATIVA atingiu três metas importantes no mesmo mês.',
  'texto_complementar','Obrigado a toda a equipe pelo trabalho, pela constância e pela contribuição para este resultado.',
  'data_referencia','2026-07')
where not exists (select 1 from public.tv_config where chave='julho_historico');

-- 2) Aniversariantes curados pela gestão (nome + dia + mês; sem idade/PII) ---
create table if not exists public.tv_aniversariantes (
  id     bigint generated by default as identity primary key,
  nome   text not null,
  dia    integer,          -- pode ser null até a gestão informar
  mes    integer not null, -- 1..12
  ativo  boolean not null default true
);
alter table public.tv_aniversariantes enable row level security;
drop policy if exists tv_aniv_sel on public.tv_aniversariantes;
create policy tv_aniv_sel on public.tv_aniversariantes for select to authenticated using (true);
drop policy if exists tv_aniv_wr on public.tv_aniversariantes;
create policy tv_aniv_wr on public.tv_aniversariantes for all to authenticated
  using (lower(auth.email()) in ('amanda.seibel@aelbra.com.br','cobranca04@aelbra.com.br'))
  with check (lower(auth.email()) in ('amanda.seibel@aelbra.com.br','cobranca04@aelbra.com.br'));

-- Seed de agosto: João e Maurício (dias a informar pela gestão).
insert into public.tv_aniversariantes (nome, dia, mes, ativo)
select * from (values ('João', null::int, 8, true), ('Maurício', null::int, 8, true)) v(nome,dia,mes,ativo)
where not exists (select 1 from public.tv_aniversariantes where mes = 8);

-- =============================================================================
-- 3) Gerador do payload — Etapa 3 (substitui a versão da Etapa 1)
-- =============================================================================
create or replace function public.tv_snapshot_calcular()
 returns jsonb
 language plpgsql
 security definer
 set search_path to 'public'
as $fn$
declare
  v_dados jsonb; v_proj jsonb; v_rank jsonb;
  v_dicas jsonb; v_elogios jsonb; v_aniv jsonb; v_msg jsonb;
  v_hoje_obj jsonb; v_mes_obj jsonb; v_metas jsonb; v_rankings jsonb; v_julho jsonb; v_avisos jsonb;
  -- projeção
  v_rec bigint; v_hon bigint; v_hon_total bigint; v_taxa_dia numeric;
  v_du_mes int; v_du_ate int; v_du_rest int;
  v_proj_rec bigint; v_proj_hon bigint; v_meta bigint; v_falta bigint; v_por_dia bigint; v_pct numeric;
  v_ant_rec bigint; v_ant_hon bigint; v_falta_3mi numeric; v_data_3mi date;
  -- hoje
  v_pag_dia int; v_maior_dia jsonb; v_top_rec_dia jsonb; v_top_qtd_dia jsonb; v_sem_pag_dia boolean;
  -- mes
  v_pag_mes int; v_media_dia numeric; v_proj_fech numeric; v_nec_dia numeric; v_meta_emp bigint := 450000;
  -- julho historico
  v_hist_ativo boolean := false; v_hist_cfg jsonb;
  v_ops text[] := array['cobranca03@aelbra.com.br','cobranca05@aelbra.com.br','cobranca06@aelbra.com.br',
                        'cobranca08@aelbra.com.br','cobranca10@aelbra.com.br','cobranca11@aelbra.com.br',
                        'cobranca12@aelbra.com.br','cobranca13@aelbra.com.br'];
  v_hoje date := (now() at time zone 'America/Sao_Paulo')::date;
  v_mes  text := to_char(v_hoje,'YYYY-MM');
  v_tem_rec boolean := to_regclass('public.recuperacao_historica') is not null;
  v_tem_elogio boolean := exists(select 1 from information_schema.columns
    where table_schema='public' and table_name='aluno_movimentacoes' and column_name='elogio_aprovado_tv');
begin
  -- ===== BLOCO A: dashboard_tv (compat Etapas 1/2) =====
  with unif as (
    select p.data_pagamento, p.valor_pago, p.valor_honorario,
           upper(btrim(coalesce(nullif(p.operador_nome,''), p.operador_email, 'Sem operador'))) as op_norm,
           p.operador_nome, p.operador_email,
           coalesce(nullif(p.cpf,''), p.aluno_nome) as aluno_ref
    from public.pagamentos p where p.data_pagamento is not null
  )
  select jsonb_build_object(
    'alunos_pagos_dia', (select count(distinct aluno_ref) from unif where data_pagamento = current_date),
    'alunos_pagos_mes', (select count(distinct aluno_ref) from unif where date_trunc('month',data_pagamento)=date_trunc('month',current_date)),
    'recuperado_dia', (select coalesce(round(sum(valor_pago)),0)::bigint from unif where data_pagamento = current_date),
    'honorarios_dia', (select coalesce(round(sum(valor_honorario)),0)::bigint from unif where data_pagamento = current_date),
    'ranking_semana', (select coalesce(jsonb_agg(jsonb_build_object('operador', op, 'pagos', pg) order by pg desc), '[]'::jsonb)
      from (select op_norm op, count(distinct aluno_ref) pg from unif where data_pagamento >= current_date - 6 group by op_norm order by pg desc limit 8) r),
    'ranking_mes', (select coalesce(jsonb_agg(jsonb_build_object('operador', op, 'pagos', pg) order by pg desc), '[]'::jsonb)
      from (select op_norm op, count(distinct aluno_ref) pg from unif where date_trunc('month',data_pagamento)=date_trunc('month',current_date) group by op_norm order by pg desc limit 8) r),
    'maior_pagamento', (select jsonb_build_object('aluno','','valor',round(valor_pago)::bigint,
        'operador',coalesce(nullif(operador_nome,''), operador_email,'-'),'quando',to_char(data_pagamento,'DD/MM'))
      from unif where date_trunc('month',data_pagamento)=date_trunc('month',current_date) order by valor_pago desc nulls last limit 1)
  ) into v_dados;

  -- ===== BLOCO B: projeção (compat) =====
  select coalesce(round(sum(valor_pago)),0)::bigint, coalesce(round(sum(valor_honorario)),0)::bigint
    into v_rec, v_hon
  from public.pagamentos where data_pagamento is not null
    and date_trunc('month',data_pagamento)=date_trunc('month',current_date);

  if v_tem_rec then
    select coalesce(round(sum(hon)),0)::bigint into v_hon_total from (
      select valor_honorario hon from public.pagamentos where data_pagamento is not null
      union all select valor_honorario from public.recuperacao_historica where data_pagamento is not null) x;
    select coalesce(sum(hon),0)/90.0 into v_taxa_dia from (
      select valor_honorario hon from public.pagamentos where data_pagamento > current_date - 90
      union all select valor_honorario from public.recuperacao_historica where data_pagamento > current_date - 90) y;
  else
    select coalesce(round(sum(valor_honorario)),0)::bigint into v_hon_total from public.pagamentos where data_pagamento is not null;
    select coalesce(sum(valor_honorario),0)/90.0 into v_taxa_dia from public.pagamentos where data_pagamento > current_date - 90;
  end if;

  v_falta_3mi := greatest(0, 3000000 - v_hon_total);
  v_data_3mi := case when v_taxa_dia > 0 and v_falta_3mi > 0 then current_date + ceil(v_falta_3mi / v_taxa_dia)::int else null end;

  select count(*) filter (where extract(dow from d) not in (0,6)),
         count(*) filter (where extract(dow from d) not in (0,6) and d <= current_date)
    into v_du_mes, v_du_ate
  from generate_series(date_trunc('month',current_date), (date_trunc('month',current_date) + interval '1 month - 1 day'), interval '1 day') d;

  v_du_ate := greatest(1, v_du_ate);           -- dias úteis transcorridos (>=1, evita /0)
  v_du_rest := greatest(0, v_du_mes - v_du_ate); -- restantes (pode ser 0)
  v_proj_rec := round(v_rec::numeric / v_du_ate * v_du_mes);
  v_proj_hon := round(v_hon::numeric / v_du_ate * v_du_mes);

  select meta_honorario::bigint into v_meta from public.metas_projecao where mes_referencia = to_char(current_date,'YYYY-MM') limit 1;
  v_pct := case when coalesce(v_meta,0) > 0 then round(v_hon::numeric / v_meta * 100, 1) else null end;
  v_falta := case when v_meta is not null then greatest(0, v_meta - v_hon) else null end;
  v_por_dia := case when v_falta is not null and v_du_rest > 0 then round(v_falta::numeric / v_du_rest) else null end;

  select proj_recuperado, proj_honorarios into v_ant_rec, v_ant_hon
  from public.tv_projecao_snapshot where dia < current_date order by dia desc limit 1;

  insert into public.tv_projecao_snapshot (dia, recuperado_mes, honorarios_mes, proj_recuperado, proj_honorarios, atualizado_em)
  values (current_date, v_rec, v_hon, v_proj_rec, v_proj_hon, now())
  on conflict (dia) do update set recuperado_mes=excluded.recuperado_mes, honorarios_mes=excluded.honorarios_mes,
    proj_recuperado=excluded.proj_recuperado, proj_honorarios=excluded.proj_honorarios, atualizado_em=now();

  v_proj := jsonb_build_object(
    'recuperado_mes', v_rec, 'honorarios_mes', v_hon, 'honorarios_total', v_hon_total,
    'data_projecao_3mi', to_char(v_data_3mi, 'DD/MM/YYYY'),
    'proj_recuperado', v_proj_rec, 'proj_honorarios', v_proj_hon,
    'meta', v_meta, 'pct_meta', v_pct, 'falta', v_falta, 'precisa_por_dia', v_por_dia,
    'dias_restantes', v_du_rest, 'dias_uteis_mes', v_du_mes,
    'delta_proj_recuperado', case when v_ant_rec is null then null else v_proj_rec - v_ant_rec end,
    'delta_proj_honorarios', case when v_ant_hon is null then null else v_proj_hon - v_ant_hon end);

  -- ===== BLOCO C: acionamentos (compat) =====
  v_rank := jsonb_build_object(
    'top_dia', coalesce((select jsonb_agg(t) from (
        select coalesce(max(u.apelido), max(u.nome), max(m.registrado_por_email)) as nome, count(*) as qtd
        from public.aluno_movimentacoes m left join public.usuarios u on lower(u.email) = lower(m.registrado_por_email)
        where public.eh_tipo_acionamento(m.tipo) and lower(m.registrado_por_email) = any(v_ops)
          and (m.registrado_em at time zone 'America/Sao_Paulo')::date = v_hoje
        group by lower(m.registrado_por_email) order by qtd desc limit 3) t),'[]'::jsonb),
    'top_mes', coalesce((select jsonb_agg(t) from (
        select coalesce(max(u.apelido), max(u.nome), max(m.registrado_por_email)) as nome, count(*) as qtd
        from public.aluno_movimentacoes m left join public.usuarios u on lower(u.email) = lower(m.registrado_por_email)
        where public.eh_tipo_acionamento(m.tipo) and lower(m.registrado_por_email) = any(v_ops)
          and to_char(m.registrado_em at time zone 'America/Sao_Paulo','YYYY-MM') = v_mes
        group by lower(m.registrado_por_email) order by qtd desc limit 3) t),'[]'::jsonb),
    'top_hon_dia', coalesce((select jsonb_agg(t) from (
        select coalesce(max(u.apelido), max(u.nome), max(p.operador_nome), max(p.operador_email)) as nome, sum(p.valor_honorario) as valor
        from public.pagamentos p left join public.usuarios u on lower(u.email) = lower(p.operador_email)
        where lower(p.operador_email) = any(v_ops) and p.data_pagamento = v_hoje
        group by lower(p.operador_email) having sum(p.valor_honorario) > 0 order by valor desc limit 3) t),'[]'::jsonb));

  -- ===== BLOCO D: dicas (compat) =====
  select coalesce(jsonb_agg(jsonb_build_object('id',id,'categoria',categoria,'titulo',titulo,'texto',texto,'ordem',ordem) order by ordem), '[]'::jsonb)
    into v_dicas from public.tv_dicas where ativo = true;

  -- ===== BLOCO E: elogios (compat) =====
  if v_tem_elogio then
    select coalesce(jsonb_agg(jsonb_build_object('id',id,'registrado_por_nome',registrado_por_nome,
              'registrado_em',registrado_em,'elogio_print_path',elogio_print_path) order by registrado_em desc), '[]'::jsonb)
      into v_elogios
    from (select id, registrado_por_nome, registrado_em, elogio_print_path from public.aluno_movimentacoes
      where status_novo = 'ELOGIO_ATENDIMENTO' and elogio_aprovado_tv = true order by registrado_em desc limit 20) e;
  else
    v_elogios := '[]'::jsonb;
  end if;

  -- ===== BLOCO F: aniversariantes (fonte curada tv_aniversariantes, mês atual) =====
  select coalesce(jsonb_agg(jsonb_build_object('nome', nome, 'dia', dia) order by dia nulls last, nome), '[]'::jsonb)
    into v_aniv
  from public.tv_aniversariantes
  where ativo = true and mes = extract(month from v_hoje);

  -- ===== BLOCO G: mensagem especial (compat com slide campanha desativado) =====
  select jsonb_build_object('titulo', titulo, 'texto', texto) into v_msg
  from public.tv_mensagem_especial where ativo = true order by atualizado_em desc limit 1;

  -- ===== BLOCO H: HOJE NA OPERAÇÃO (só pagamentos confirmados = tabela pagamentos) =====
  select count(*)::int into v_pag_dia from public.pagamentos where data_pagamento = current_date;
  v_sem_pag_dia := (v_pag_dia = 0);

  select jsonb_build_object('valor', round(valor_pago)::bigint,
           'operador', coalesce(nullif(operador_nome,''), operador_email, '-'))
    into v_maior_dia
  from public.pagamentos where data_pagamento = current_date order by valor_pago desc nulls last limit 1;

  select jsonb_build_object('operador', op, 'valor', vl) into v_top_rec_dia from (
    select upper(btrim(coalesce(nullif(operador_nome,''), operador_email))) op, round(sum(valor_pago))::bigint vl
    from public.pagamentos where data_pagamento = current_date
      and coalesce(nullif(operador_nome,''), operador_email) is not null
    group by 1 order by vl desc limit 1) a;

  select jsonb_build_object('operador', op, 'qtd', q) into v_top_qtd_dia from (
    select upper(btrim(coalesce(nullif(operador_nome,''), operador_email))) op, count(*) q
    from public.pagamentos where data_pagamento = current_date
      and coalesce(nullif(operador_nome,''), operador_email) is not null
    group by 1 order by q desc, op asc limit 1) a;

  v_hoje_obj := jsonb_build_object(
    'recuperado', (v_dados->>'recuperado_dia')::bigint,
    'honorarios', (v_dados->>'honorarios_dia')::bigint,
    'pagamentos_confirmados', v_pag_dia,
    'maior_pagamento', v_maior_dia,
    'top_recuperador', v_top_rec_dia,
    'top_qtd', v_top_qtd_dia,
    'sem_pagamentos', v_sem_pag_dia);

  -- ===== BLOCO I: RESULTADO DO MÊS =====
  select count(*)::int into v_pag_mes from public.pagamentos
   where date_trunc('month',data_pagamento)=date_trunc('month',current_date);

  v_media_dia := round(v_rec::numeric / v_du_ate);                    -- /0 protegido (v_du_ate>=1)
  v_proj_fech := round(v_media_dia * v_du_mes);
  v_nec_dia := case when v_hon >= v_meta_emp then null                 -- meta já atingida
                    when v_du_rest = 0 then null                       -- sem dias restantes
                    else round((v_meta_emp - v_hon)::numeric / v_du_rest) end;

  v_mes_obj := jsonb_build_object(
    'recuperado', v_rec, 'honorarios', v_hon, 'pagamentos_confirmados', v_pag_mes,
    'media_diaria', v_media_dia, 'projecao_fechamento', v_proj_fech,
    'dias_uteis_mes', v_du_mes, 'dias_uteis_transcorridos', v_du_ate, 'dias_uteis_restantes', v_du_rest,
    'meta_empresa', v_meta_emp, 'meta_atingida', (v_hon >= v_meta_emp),
    'necessidade_diaria', v_nec_dia,
    'comparacao', jsonb_build_object('realizado', v_rec, 'projetado', v_proj_fech, 'diferenca', v_proj_fech - v_rec),
    'estimativa_aviso', 'Projeção estimada com base no ritmo atual.');

  -- ===== BLOCO J: METAS (3 metas; pct sem teto; conquista quando atingida) =====
  select jsonb_agg(m order by ord) into v_metas from (
    select 1 ord, public._tv_meta_obj('empresa','Meta da empresa', 450000, v_hon, 'mensal', v_proj_hon, v_du_rest) m
    union all
    select 2, public._tv_meta_obj('magic','Magic Number', 500000, v_hon, 'mensal', v_proj_hon, v_du_rest)
    union all
    select 3, public._tv_meta_obj('marco','Marco histórico', 3000000, v_hon_total, 'total', v_hon_total, v_du_rest)
  ) z;

  -- ===== BLOCO K: RANKINGS E DESTAQUES (só recuperado confirmado; sem honorário) =====
  v_rankings := jsonb_build_object(
    'melhor_dia', (select jsonb_build_object('operador', op) from (
        select upper(btrim(coalesce(nullif(operador_nome,''),operador_email))) op, sum(valor_pago) v, count(*) q
        from public.pagamentos where data_pagamento = current_date
          and coalesce(nullif(operador_nome,''),operador_email) is not null
        group by 1 order by v desc, q desc, op asc limit 1) a),
    'melhor_mes', (select jsonb_build_object('operador', op) from (
        select upper(btrim(coalesce(nullif(operador_nome,''),operador_email))) op, sum(valor_pago) v, count(*) q
        from public.pagamentos where date_trunc('month',data_pagamento)=date_trunc('month',current_date)
          and coalesce(nullif(operador_nome,''),operador_email) is not null
        group by 1 order by v desc, q desc, op asc limit 1) a),
    'top3_mes', coalesce((select jsonb_agg(jsonb_build_object('operador', op) order by v desc, q desc, op asc) from (
        select upper(btrim(coalesce(nullif(operador_nome,''),operador_email))) op, sum(valor_pago) v, count(*) q
        from public.pagamentos where date_trunc('month',data_pagamento)=date_trunc('month',current_date)
          and coalesce(nullif(operador_nome,''),operador_email) is not null
        group by 1 order by v desc, q desc, op asc limit 3) a), '[]'::jsonb),
    'mais_pagos_dia', (select jsonb_build_object('operador', op, 'qtd', q) from (
        select upper(btrim(coalesce(nullif(operador_nome,''),operador_email))) op, count(*) q
        from public.pagamentos where data_pagamento = current_date
          and coalesce(nullif(operador_nome,''),operador_email) is not null
        group by 1 order by q desc, op asc limit 1) a),
    'maior_pagamento_mes', (select jsonb_build_object('valor', round(valor_pago)::bigint,
          'operador', coalesce(nullif(operador_nome,''),operador_email,'-'))
        from public.pagamentos where date_trunc('month',data_pagamento)=date_trunc('month',current_date)
        order by valor_pago desc nulls last limit 1));

  -- ===== BLOCO L: JULHO HISTÓRICO (ativável por tv_config) =====
  select ativo, valor into v_hist_ativo, v_hist_cfg from public.tv_config where chave='julho_historico';
  if coalesce(v_hist_ativo,false) then
    v_julho := jsonb_build_object(
      'ativo', true,
      'titulo', coalesce(v_hist_cfg->>'titulo','Julho Histórico'),
      'texto_principal', v_hist_cfg->>'texto_principal',
      'texto_complementar', v_hist_cfg->>'texto_complementar',
      'data_referencia', v_hist_cfg->>'data_referencia',
      'metas', jsonb_build_array(
        public._tv_meta_hist('Meta da empresa', 450000, v_hon),
        public._tv_meta_hist('Magic Number', 500000, v_hon),
        public._tv_meta_hist('Marco de R$ 3 milhões', 3000000, v_hon_total)));
  else
    v_julho := jsonb_build_object('ativo', false);
  end if;

  -- ===== BLOCO M: AVISOS (ativos, dentro da vigência, por prioridade) =====
  select coalesce(jsonb_agg(jsonb_build_object('titulo',titulo,'mensagem',texto,'prioridade',prioridade)
           order by prioridade desc, data_final asc nulls last, atualizado_em desc), '[]'::jsonb)
    into v_avisos
  from public.tv_mensagem_especial
  where ativo = true
    and (data_inicial is null or data_inicial <= current_date)
    and (data_final   is null or data_final   >= current_date);

  return jsonb_build_object(
    'dados', v_dados, 'proj', v_proj, 'rank', v_rank,
    'dicas', v_dicas, 'elogios', v_elogios, 'aniversariantes', v_aniv, 'mensagem_especial', v_msg,
    -- Etapa 3:
    'hoje', v_hoje_obj, 'mes', v_mes_obj, 'metas', v_metas,
    'rankings', v_rankings, 'julho_historico', v_julho, 'avisos', v_avisos);
end;
$fn$;

-- Helper: monta um objeto de meta com todas as regras (pct sem teto, conquista).
create or replace function public._tv_meta_obj(
  p_id text, p_nome text, p_alvo bigint, p_realizado bigint, p_tipo text, p_proj bigint, p_du_rest int)
 returns jsonb language plpgsql stable security definer set search_path to 'public' as $fn$
declare
  v_pct numeric := case when p_alvo > 0 then round(p_realizado::numeric / p_alvo * 100, 1) else null end;
  v_atingida boolean := p_realizado >= p_alvo;
  v_restante bigint := greatest(0, p_alvo - p_realizado);
  v_excedente bigint := greatest(0, p_realizado - p_alvo);
  v_sit text; v_ritmo numeric; v_data date;
begin
  if v_atingida then
    v_sit := 'Meta atingida';
  elsif p_proj >= p_alvo then
    v_sit := 'No ritmo';
  elsif p_proj >= p_alvo * 0.9 then
    v_sit := 'Atenção';
  else
    v_sit := 'Abaixo do ritmo';
  end if;

  v_ritmo := case when v_atingida or p_du_rest = 0 then null
                  else round(v_restante::numeric / p_du_rest) end;

  -- data de atingimento só para metas mensais de honorário (histórico diário disponível)
  if v_atingida and p_tipo = 'mensal' then
    select min(dia) into v_data from public.tv_projecao_snapshot
     where honorarios_mes >= p_alvo and date_trunc('month',dia)=date_trunc('month',current_date);
  end if;

  return jsonb_build_object(
    'id', p_id, 'nome', p_nome, 'tipo', p_tipo, 'alvo', p_alvo, 'realizado', p_realizado,
    'pct', v_pct, 'restante', v_restante, 'excedente', v_excedente, 'atingida', v_atingida,
    'situacao', v_sit, 'ritmo_necessario', v_ritmo,
    'data_atingimento', to_char(v_data,'DD/MM/YYYY'),
    'mensagem', case when v_atingida then 'Meta alcançada. Este resultado representa o trabalho conjunto de toda a equipe.' else null end);
end; $fn$;

-- Helper: resumo curto de meta para a tela Julho Histórico.
create or replace function public._tv_meta_hist(p_nome text, p_alvo bigint, p_realizado bigint)
 returns jsonb language sql immutable set search_path to 'public' as $fn$
  select jsonb_build_object('nome', p_nome, 'alvo', p_alvo, 'realizado', p_realizado,
    'pct', case when p_alvo>0 then round(p_realizado::numeric/p_alvo*100,1) else null end,
    'excedente', greatest(0, p_realizado - p_alvo));
$fn$;

revoke all on function public._tv_meta_obj(text,text,bigint,bigint,text,bigint,int) from public, anon, authenticated;
revoke all on function public._tv_meta_hist(text,bigint,bigint) from public, anon, authenticated;
