-- =============================================================================
-- TV ReATIVA — ARQUITETURA DE SNAPSHOT (sem polling, sem cálculo ao exibir)
-- =============================================================================
-- Objetivo: a TV deixa de calcular tudo AO VIVO (3 RPCs pesadas + 2 selects por
-- ciclo) e passa a LER UM ÚNICO snapshot leve (tv_snapshot_ler = 1 leitura).
-- A geração do snapshot ocorre SÓ quando Amanda/Fernanda clicam em "Atualizar
-- projeção" (mesmo gatilho da projeção e dos snapshots gerenciais).
--
-- Espelha o padrão já validado de projecao_snapshot / snapshot_gerencial:
--   * tabela com RLS deny-all (só as funções SECURITY DEFINER leem/escrevem);
--   * *_atualizar restrita por allowlist de e-mail (Amanda + Fernanda) com lock
--     de execução única e preservação do snapshot anterior em caso de falha;
--   * *_ler leve para a exibição.
--
-- AUTOSSUFICIENTE: o gerador NÃO chama dashboard_tv/dashboard_tv_projecao/
-- acionamentos_ranking (que existem apenas em produção, fora do versionamento).
-- A lógica dessas 3 RPCs foi trazida INLINE aqui (fiel à definição de produção),
-- de modo que a migration provisiona e valida de ponta a ponta também no staging.
-- As guardas abaixo criam apenas o que faltar; em produção viram no-op.
--
-- PRIVACIDADE: o payload da TV NÃO carrega CPF, telefone nem nome de aluno.
--   * maior_pagamento vai com aluno='' (idêntico à dashboard_tv de produção);
--   * elogios levam só autor (colaborador), data e caminho da imagem;
--   * aniversariantes são da EQUIPE (usuarios.aniversario), nunca de alunos.
--
-- NÃO APLICAR EM PRODUÇÃO sem autorização. Destinado a validação em staging.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 0) Dependências (guardas) — criam só se faltarem (no-op em produção).
-- ---------------------------------------------------------------------------
do $do$
begin
  -- helper de classificação de acionamento (existe em produção)
  if to_regprocedure('public.eh_tipo_acionamento(text)') is null then
    execute $fn$
      create function public.eh_tipo_acionamento(p_tipo text)
      returns boolean language sql immutable set search_path to 'public' as $b$
        select coalesce(p_tipo,'') in (
          'FINALIZACAO_ATENDIMENTO','FINALIZACAO','ACAO_MASSIVA_EXTERNA','ACAO_MASSIVA_EXTERNA_EMAIL','CONTATO',
          'LINK_ENVIADO_AO_ALUNO','SOLICITACAO_LINK_PAGAMENTO','COMPROVANTE_ENVIADO_BAIXA',
          'QUITADO_MANUAL','TERMO_ENVIADO_ADM','RETORNO_ADM_CRIADO','RETORNO_ADM_CONCLUIDO'
        );
      $b$;
    $fn$;
  end if;
end
$do$;

-- Conteúdos ativos da TV (dicas). Existe em produção; guarda p/ staging.
create table if not exists public.tv_dicas (
  id         bigint generated by default as identity primary key,
  categoria  text,
  titulo     text,
  texto      text,
  ordem      integer default 0,
  ativo      boolean default true,
  criado_em  timestamptz default now()
);

-- Histórico diário usado para o delta da projeção (subiu/caiu vs ontem).
create table if not exists public.tv_projecao_snapshot (
  dia             date primary key,
  recuperado_mes  bigint,
  honorarios_mes  bigint,
  proj_recuperado bigint,
  proj_honorarios bigint,
  atualizado_em   timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- 1) Mensagem especial da TV (fonte editável do slide "campanha").
--    Uma linha ativa por vez; o gerador captura a mais recente ativa.
-- ---------------------------------------------------------------------------
create table if not exists public.tv_mensagem_especial (
  id             bigint generated by default as identity primary key,
  titulo         text,
  texto          text,
  ativo          boolean not null default true,
  atualizado_em  timestamptz not null default now(),
  atualizado_por text
);
alter table public.tv_mensagem_especial enable row level security;
-- Leitura por qualquer autenticado; escrita só gestão (via política simples).
drop policy if exists tv_msg_sel on public.tv_mensagem_especial;
create policy tv_msg_sel on public.tv_mensagem_especial for select to authenticated using (true);
drop policy if exists tv_msg_wr on public.tv_mensagem_especial;
create policy tv_msg_wr on public.tv_mensagem_especial for all to authenticated
  using (lower(auth.email()) in ('amanda.seibel@aelbra.com.br','cobranca04@aelbra.com.br'))
  with check (lower(auth.email()) in ('amanda.seibel@aelbra.com.br','cobranca04@aelbra.com.br'));

-- Seed: preserva o texto da campanha atual da TV como default editável.
insert into public.tv_mensagem_especial (titulo, texto, ativo, atualizado_por)
select '🔥 BORA TIME! 🔥', 'Meta do mês: R$ 500 mil em honorários', true, 'seed'
where not exists (select 1 from public.tv_mensagem_especial);

-- ---------------------------------------------------------------------------
-- 2) Tabela de snapshot da TV (1 única linha). RLS deny-all: só as funções
--    SECURITY DEFINER acessam (evita PostgREST expor o payload cru).
-- ---------------------------------------------------------------------------
create table if not exists public.tv_snapshot (
  id            boolean primary key default true,
  versao        bigint  not null default 0,
  payload       jsonb,
  status        text    not null default 'vazio',  -- ok | erro | vazio
  gerado_em     timestamptz,
  gerado_por    text,
  duracao_ms    integer,
  erro_resumo   text,
  constraint tv_snapshot_singleton check (id)
);
alter table public.tv_snapshot enable row level security;
-- sem policies => nenhum acesso direto por PostgREST; só via RPCs definer.

-- ---------------------------------------------------------------------------
-- 3) Cálculo do payload da TV (INLINE, fiel às 3 RPCs de produção).
--    Uma varredura por bloco; usado só pelo gerador.
-- ---------------------------------------------------------------------------
create or replace function public.tv_snapshot_calcular()
 returns jsonb
 language plpgsql
 security definer
 set search_path to 'public'
as $fn$
declare
  v_dados jsonb; v_proj jsonb; v_rank jsonb;
  v_dicas jsonb; v_elogios jsonb; v_aniv jsonb; v_msg jsonb;
  -- projeção (espelha dashboard_tv_projecao)
  v_rec bigint; v_hon bigint; v_hon_total bigint; v_taxa_dia numeric;
  v_du_mes int; v_du_ate int; v_du_rest int;
  v_proj_rec bigint; v_proj_hon bigint; v_meta bigint; v_falta bigint; v_por_dia bigint; v_pct numeric;
  v_ant_rec bigint; v_ant_hon bigint; v_falta_3mi numeric; v_data_3mi date;
  v_ops text[] := array['cobranca03@aelbra.com.br','cobranca05@aelbra.com.br','cobranca06@aelbra.com.br',
                        'cobranca08@aelbra.com.br','cobranca10@aelbra.com.br','cobranca11@aelbra.com.br',
                        'cobranca12@aelbra.com.br','cobranca13@aelbra.com.br'];
  v_hoje date := (now() at time zone 'America/Sao_Paulo')::date;
  v_mes  text := to_char(v_hoje,'YYYY-MM');
  v_tem_rec boolean := to_regclass('public.recuperacao_historica') is not null;
  v_tem_elogio boolean := exists(select 1 from information_schema.columns
    where table_schema='public' and table_name='aluno_movimentacoes' and column_name='elogio_aprovado_tv');
begin
  -- ===== BLOCO A: dashboard_tv (rankings de alunos, maior pagamento) =====
  with unif as (
    select p.data_pagamento, p.valor_pago, p.valor_honorario,
           upper(btrim(coalesce(nullif(p.operador_nome,''), p.operador_email, 'Sem operador'))) as op_norm,
           p.operador_nome, p.operador_email,
           coalesce(nullif(p.cpf,''), p.aluno_nome) as aluno_ref
    from public.pagamentos p where p.data_pagamento is not null
  )
  select jsonb_build_object(
    'alunos_pagos_dia', (select count(distinct aluno_ref) from unif where data_pagamento = current_date),
    'alunos_pagos_mes', (select count(distinct aluno_ref) from unif where date_trunc('month',data_pagamento)=date_trunc('month',current_date)),
    'recuperado_dia', (select coalesce(round(sum(valor_pago)),0)::bigint from unif where data_pagamento = current_date),
    'honorarios_dia', (select coalesce(round(sum(valor_honorario)),0)::bigint from unif where data_pagamento = current_date),
    'ranking_semana', (
      select coalesce(jsonb_agg(jsonb_build_object('operador', op, 'pagos', pg) order by pg desc), '[]'::jsonb)
      from (select op_norm op, count(distinct aluno_ref) pg from unif where data_pagamento >= current_date - 6 group by op_norm order by pg desc limit 8) r),
    'ranking_mes', (
      select coalesce(jsonb_agg(jsonb_build_object('operador', op, 'pagos', pg) order by pg desc), '[]'::jsonb)
      from (select op_norm op, count(distinct aluno_ref) pg from unif where date_trunc('month',data_pagamento)=date_trunc('month',current_date) group by op_norm order by pg desc limit 8) r),
    'maior_pagamento', (
      select jsonb_build_object('aluno', '', 'valor', round(valor_pago)::bigint,
                               'operador', coalesce(nullif(operador_nome,''), operador_email, '-'),
                               'quando', to_char(data_pagamento, 'DD/MM'))
      from unif where date_trunc('month',data_pagamento)=date_trunc('month',current_date)
      order by valor_pago desc nulls last limit 1)
  ) into v_dados;

  -- ===== BLOCO B: dashboard_tv_projecao (honorários, projeção, meta, 3mi) =====
  select coalesce(round(sum(valor_pago)),0)::bigint, coalesce(round(sum(valor_honorario)),0)::bigint
    into v_rec, v_hon
  from public.pagamentos where data_pagamento is not null
    and date_trunc('month',data_pagamento)=date_trunc('month',current_date);

  if v_tem_rec then
    select coalesce(round(sum(hon)),0)::bigint into v_hon_total from (
      select valor_honorario hon from public.pagamentos where data_pagamento is not null
      union all select valor_honorario from public.recuperacao_historica where data_pagamento is not null) x;
    select coalesce(sum(hon),0)/90.0 into v_taxa_dia from (
      select valor_honorario hon from public.pagamentos where data_pagamento > current_date - 90
      union all select valor_honorario from public.recuperacao_historica where data_pagamento > current_date - 90) y;
  else
    select coalesce(round(sum(valor_honorario)),0)::bigint into v_hon_total from public.pagamentos where data_pagamento is not null;
    select coalesce(sum(valor_honorario),0)/90.0 into v_taxa_dia from public.pagamentos where data_pagamento > current_date - 90;
  end if;

  v_falta_3mi := greatest(0, 3000000 - v_hon_total);
  v_data_3mi := case when v_taxa_dia > 0 and v_falta_3mi > 0 then current_date + ceil(v_falta_3mi / v_taxa_dia)::int else null end;

  select count(*) filter (where extract(dow from d) not in (0,6)),
         count(*) filter (where extract(dow from d) not in (0,6) and d <= current_date)
    into v_du_mes, v_du_ate
  from generate_series(date_trunc('month',current_date), (date_trunc('month',current_date) + interval '1 month - 1 day'), interval '1 day') d;

  v_du_ate := greatest(1, v_du_ate);
  v_du_rest := greatest(1, v_du_mes - v_du_ate);
  v_proj_rec := round(v_rec::numeric / v_du_ate * v_du_mes);
  v_proj_hon := round(v_hon::numeric / v_du_ate * v_du_mes);

  select meta_honorario::bigint into v_meta from public.metas_projecao where mes_referencia = to_char(current_date,'YYYY-MM') limit 1;
  v_pct := case when coalesce(v_meta,0) > 0 then round(v_hon::numeric / v_meta * 100, 1) else null end;
  v_falta := case when v_meta is not null then greatest(0, v_meta - v_hon) else null end;
  v_por_dia := case when v_falta is not null then round(v_falta::numeric / v_du_rest) else null end;

  select proj_recuperado, proj_honorarios into v_ant_rec, v_ant_hon
  from public.tv_projecao_snapshot where dia < current_date order by dia desc limit 1;

  -- registra o dia no histórico (para o delta de amanhã), como a RPC original
  insert into public.tv_projecao_snapshot (dia, recuperado_mes, honorarios_mes, proj_recuperado, proj_honorarios, atualizado_em)
  values (current_date, v_rec, v_hon, v_proj_rec, v_proj_hon, now())
  on conflict (dia) do update set recuperado_mes=excluded.recuperado_mes, honorarios_mes=excluded.honorarios_mes,
    proj_recuperado=excluded.proj_recuperado, proj_honorarios=excluded.proj_honorarios, atualizado_em=now();

  v_proj := jsonb_build_object(
    'recuperado_mes', v_rec, 'honorarios_mes', v_hon, 'honorarios_total', v_hon_total,
    'data_projecao_3mi', to_char(v_data_3mi, 'DD/MM/YYYY'),
    'proj_recuperado', v_proj_rec, 'proj_honorarios', v_proj_hon,
    'meta', v_meta, 'pct_meta', v_pct, 'falta', v_falta, 'precisa_por_dia', v_por_dia,
    'dias_restantes', v_du_rest, 'dias_uteis_mes', v_du_mes,
    'delta_proj_recuperado', case when v_ant_rec is null then null else v_proj_rec - v_ant_rec end,
    'delta_proj_honorarios', case when v_ant_hon is null then null else v_proj_hon - v_ant_hon end);

  -- ===== BLOCO C: acionamentos_ranking (top 3 dia/mês/honorário) =====
  v_rank := jsonb_build_object(
    'top_dia', coalesce((select jsonb_agg(t) from (
        select coalesce(max(u.apelido), max(u.nome), max(m.registrado_por_email)) as nome, count(*) as qtd
        from public.aluno_movimentacoes m
        left join public.usuarios u on lower(u.email) = lower(m.registrado_por_email)
        where public.eh_tipo_acionamento(m.tipo) and lower(m.registrado_por_email) = any(v_ops)
          and (m.registrado_em at time zone 'America/Sao_Paulo')::date = v_hoje
        group by lower(m.registrado_por_email) order by qtd desc limit 3) t),'[]'::jsonb),
    'top_mes', coalesce((select jsonb_agg(t) from (
        select coalesce(max(u.apelido), max(u.nome), max(m.registrado_por_email)) as nome, count(*) as qtd
        from public.aluno_movimentacoes m
        left join public.usuarios u on lower(u.email) = lower(m.registrado_por_email)
        where public.eh_tipo_acionamento(m.tipo) and lower(m.registrado_por_email) = any(v_ops)
          and to_char(m.registrado_em at time zone 'America/Sao_Paulo','YYYY-MM') = v_mes
        group by lower(m.registrado_por_email) order by qtd desc limit 3) t),'[]'::jsonb),
    'top_hon_dia', coalesce((select jsonb_agg(t) from (
        select coalesce(max(u.apelido), max(u.nome), max(p.operador_nome), max(p.operador_email)) as nome, sum(p.valor_honorario) as valor
        from public.pagamentos p
        left join public.usuarios u on lower(u.email) = lower(p.operador_email)
        where lower(p.operador_email) = any(v_ops) and p.data_pagamento = v_hoje
        group by lower(p.operador_email) having sum(p.valor_honorario) > 0
        order by valor desc limit 3) t),'[]'::jsonb));

  -- ===== BLOCO D: conteúdos ativos (dicas) =====
  select coalesce(jsonb_agg(jsonb_build_object('id',id,'categoria',categoria,'titulo',titulo,'texto',texto,'ordem',ordem) order by ordem), '[]'::jsonb)
    into v_dicas from public.tv_dicas where ativo = true;

  -- ===== BLOCO E: elogios aprovados (sem PII de aluno: só autor/data/imagem) =====
  if v_tem_elogio then
    select coalesce(jsonb_agg(jsonb_build_object(
              'id', id, 'registrado_por_nome', registrado_por_nome,
              'registrado_em', registrado_em, 'elogio_print_path', elogio_print_path
            ) order by registrado_em desc), '[]'::jsonb)
      into v_elogios
    from (
      select id, registrado_por_nome, registrado_em, elogio_print_path
      from public.aluno_movimentacoes
      where status_novo = 'ELOGIO_ATENDIMENTO' and elogio_aprovado_tv = true
      order by registrado_em desc limit 20
    ) e;
  else
    v_elogios := '[]'::jsonb;
  end if;

  -- ===== BLOCO F: aniversariantes do mês (EQUIPE, via usuarios.aniversario) =====
  select coalesce(jsonb_agg(jsonb_build_object(
            'nome', coalesce(nullif(apelido,''), nome),
            'dia', extract(day from aniversario)::int,
            'mes', extract(month from aniversario)::int
          ) order by extract(day from aniversario)), '[]'::jsonb)
    into v_aniv
  from public.usuarios
  where aniversario is not null and extract(month from aniversario) = extract(month from v_hoje);

  -- ===== BLOCO G: mensagem especial ativa (mais recente) =====
  select jsonb_build_object('titulo', titulo, 'texto', texto)
    into v_msg
  from public.tv_mensagem_especial where ativo = true order by atualizado_em desc limit 1;

  return jsonb_build_object(
    'dados', v_dados, 'proj', v_proj, 'rank', v_rank,
    'dicas', v_dicas, 'elogios', v_elogios,
    'aniversariantes', v_aniv, 'mensagem_especial', v_msg);
end;
$fn$;

-- ---------------------------------------------------------------------------
-- 4) Gerador do snapshot — restrito a Amanda/Fernanda (ou service_role).
--    Atômico: computa todo o payload numa variável e faz UM swap. Em falha,
--    preserva o snapshot anterior (payload/versão) e registra status='erro'.
-- ---------------------------------------------------------------------------
create or replace function public.tv_snapshot_atualizar()
 returns jsonb
 language plpgsql
 security definer
 set search_path to 'public'
 set statement_timeout to '30s'
as $fn$
declare
  v_email text := lower(auth.email());
  v_got boolean; v_t0 timestamptz; v_now timestamptz; v_ms int;
  v_payload jsonb; v_versao bigint;
begin
  if coalesce(auth.role(),'') <> 'service_role'
     and coalesce(v_email,'') not in ('amanda.seibel@aelbra.com.br','cobranca04@aelbra.com.br') then
    raise exception 'Acesso negado: apenas Amanda e Fernanda podem atualizar a TV (usuario=%).',
      coalesce(v_email,'(anonimo)') using errcode = '42501';
  end if;

  v_got := pg_try_advisory_xact_lock(hashtext('tv_snapshot_atualizar')::int, 0);
  if not v_got then
    raise exception 'Ja existe uma atualizacao da TV em andamento.' using errcode = '55P03';
  end if;

  -- garante a linha singleton
  insert into public.tv_snapshot (id) values (true) on conflict (id) do nothing;

  v_t0 := clock_timestamp(); v_now := now();
  begin
    if coalesce(current_setting('tv.forcar_erro', true),'') = '1' then
      raise exception 'FALHA_SIMULADA_TESTE';
    end if;

    -- computa TODO o payload antes de tocar no snapshot anterior
    v_payload := public.tv_snapshot_calcular();
    v_ms := round(extract(milliseconds from clock_timestamp() - v_t0));

    -- swap atômico (só aqui o anterior é substituído)
    update public.tv_snapshot
       set versao = versao + 1, payload = v_payload, status = 'ok',
           gerado_em = v_now, gerado_por = coalesce(v_email,'service_role'),
           duracao_ms = v_ms, erro_resumo = null
     where id = true
     returning versao into v_versao;
  exception when others then
    -- preserva payload/versão anteriores; marca só o status/erro
    update public.tv_snapshot
       set status = 'erro', erro_resumo = left(sqlerrm, 300),
           gerado_em = v_now, gerado_por = coalesce(v_email,'service_role')
     where id = true;
    return jsonb_build_object('status','erro','erro_resumo',left(sqlerrm,300));
  end;

  return jsonb_build_object('status','ok','versao',v_versao,'duracao_ms',v_ms,
    'gerado_em', v_now, 'gerado_por', coalesce(v_email,'service_role'));
end;
$fn$;

-- ---------------------------------------------------------------------------
-- 5) Leitura leve para a TV — 1 chamada, sem cálculo. Qualquer autenticado.
-- ---------------------------------------------------------------------------
create or replace function public.tv_snapshot_ler()
 returns jsonb
 language plpgsql
 stable security definer
 set search_path to 'public'
as $fn$
declare
  v_row public.tv_snapshot%rowtype;
begin
  if coalesce(auth.role(),'') not in ('authenticated','service_role') then
    raise exception 'Acesso negado: requer usuario autenticado.' using errcode = '42501';
  end if;

  select * into v_row from public.tv_snapshot where id = true;

  if not found or v_row.payload is null then
    return jsonb_build_object('status','vazio','versao',coalesce(v_row.versao,0),
      'payload',null,'gerado_em',v_row.gerado_em,'gerado_por',v_row.gerado_por,'erro_resumo',v_row.erro_resumo);
  end if;

  return jsonb_build_object(
    'status', v_row.status, 'versao', v_row.versao, 'payload', v_row.payload,
    'gerado_em', v_row.gerado_em, 'gerado_por', v_row.gerado_por,
    'duracao_ms', v_row.duracao_ms, 'erro_resumo', v_row.erro_resumo);
end;
$fn$;

-- ---------------------------------------------------------------------------
-- 6) Versão leve de verificação — só a versão/timestamp, sem trazer o payload.
--    Usada pela TV entre ciclos para decidir se recarrega (custo mínimo).
-- ---------------------------------------------------------------------------
create or replace function public.tv_snapshot_versao()
 returns jsonb
 language plpgsql
 stable security definer
 set search_path to 'public'
as $fn$
declare v_versao bigint; v_gerado timestamptz;
begin
  if coalesce(auth.role(),'') not in ('authenticated','service_role') then
    raise exception 'Acesso negado: requer usuario autenticado.' using errcode = '42501';
  end if;
  select versao, gerado_em into v_versao, v_gerado from public.tv_snapshot where id = true;
  return jsonb_build_object('versao', coalesce(v_versao,0), 'gerado_em', v_gerado);
end;
$fn$;

-- ---------------------------------------------------------------------------
-- 7) Grants (revoga anon; concede execução aos papéis certos).
-- ---------------------------------------------------------------------------
revoke all on function public.tv_snapshot_calcular() from public, anon;
revoke all on function public.tv_snapshot_atualizar() from public, anon;
revoke all on function public.tv_snapshot_ler() from public, anon;
revoke all on function public.tv_snapshot_versao() from public, anon;

grant execute on function public.tv_snapshot_atualizar() to authenticated;  -- backend valida allowlist
grant execute on function public.tv_snapshot_ler() to authenticated;
grant execute on function public.tv_snapshot_versao() to authenticated;
-- tv_snapshot_calcular é uso interno do gerador (tem efeito colateral: grava
-- histórico em tv_projecao_snapshot). O Supabase concede execute a authenticated
-- por padrão, então revogamos explicitamente para deixá-la só ao definer.
revoke execute on function public.tv_snapshot_calcular() from authenticated;
